### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by itsrvsingh** [projectdiscovery/naabu#1012]
go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
../pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by dogancanbakir** [comment]
See https://github.com/projectdiscovery/naabu/issues/743#issuecomment-1655440048 for the solution.
