### ISSUE TITLE
FreeBSD scan_common.go:62:23: undefined: routing.New

### ISSUE THREAD

**Issue by dualfade** [projectdiscovery/naabu#1015]
> uname -a
FreeBSD freebsd 14.0-RELEASE-p6

Fetched src to manually compile but wanted to share the error below. Looking like scan_common.go is a new feature ( 27 days ).  v2.2.1 compiled fine. 

> go version
go version go1.22.1 freebsd/amd64

user@freebsd:pts/0-> /tmp (0)
> go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
github.com/projectdiscovery/naabu/v2/pkg/scan
/home/user/Workspace/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.3.0/pkg/scan/scan_common.go:62:23: undefined: routing.New
user@freebsd:pts/0-> /tmp (1)
>

Thanks in advance --

**Comment by bsdtr** [comment]
Hi, I fixed this error here: https://github.com/projectdiscovery/naabu/pull/1299
