### ISSUE TITLE
Port spray support

### ISSUE THREAD

**Issue by lovelyjuice** [projectdiscovery/naabu#1052]
### Please describe your feature request:
Provide port-spray option like `-scan-strategy template-spray` in nuclei.

### Describe the use case of this feature:
When scanning a large number of IPs, reduce the scanning rate per IPs.

**Comment by GeorginaReeder** [comment]
Thanks so much for your feature request @lovelyjuice , we'll take a look into this :)

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Comment by Mzack9999** [comment]
@lovelyjuice This is already supported internally as naabu shuffle randomly ip and ports, so this is the default modality
