### ISSUE TITLE
[feature] Make alpine great again!

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [projectdiscovery/naabu#106]
**Is your feature request related to a problem? Please describe.**
It seems that it's nothing new that you can't build naabu on the alpine base-image. I'm currently building a little "recon" image and I got an image with 1.22GB in the final stage. This is due to me being restricted to the Buster Slim image. This is insane! The ultimate solution would be to make the native extensions building on musl.

**Describe the solution you'd like**
After days of googling I think I've found a solution and luckily it's on GitHub! Please see the provided PR in this [issue](https://github.com/lxc/lxd/issues/4848).

I'd have done it myself but unfortunately I can't code in Go :) please let me know if I can help any further (eg testing out the new image)

**Comment by ehsandeep** [comment]
Added here https://github.com/projectdiscovery/naabu/blob/master/Dockerfile
