### ISSUE TITLE
[Bug] With or without the -exclude-cdn flag, Naabu will create the runner and make GET requests

### ISSUE THREAD

**Issue by 003random** [projectdiscovery/naabu#107]
**Describe the bug**
I would like a port scanner to be a port scanner only. Currently Naabu is making GET requests which from time to time fail because either the DNS lookup had an I/O time out or the page was acting weird.
Docs say that the CDN check is optional but I bet there is a mistake somewhere because with or without the flag, it creates a runner which means it sends requests to cloudflare, ipinfo and other sites.

**Comment by 003random** [comment]
Might be because the excludeCDN name is confusing and the code is full of options.CDN = !options.ExcludeCDN and if !options.CDN. its getting flipped everywhere...

**Comment by 003random** [comment]
Other than that and not being able to use it as a package because the results get stored on an unexported obj, its great tho! The speed is good and i love the take ip:port combo from bucket approach which is good for load distribution

**Comment by bauthard** [comment]
Hi @003random, 

Thank you for the review, we already fixed this here https://github.com/projectdiscovery/naabu/pull/93, now it's optional flag + we make use of cached data, these changes are live in the master code and we will we creating new release after some bug fixes.

**Comment by 003random** [comment]
So when you don't specify any flags apart from -host and -p then the CDN check will not happen? @bauthard.
That seems to be what optional means.
But when pulling the latest version and just adding a simple `fmt.Println("Initializing new CDN checker")` on line 130 of scan.go in the scan pkg, followed by running Naabu `go run main.go -host 127.0.0.1 -p 80,443`, you will notice in the Naabu output it has printed `Initializing new CDN checker` which means it has initialized the CDN checker client which means it has sent requests to cloudflare.com and other CDN providers to fetch their IP addresses right?

**Comment by 003random** [comment]
Probably because it uses options.Cdn which is initialized with `Cdn:     !options.ExcludeCDN,` and ExcludeCDN is set to false by default which means options.Cdn will be true by default.
And when options.Cdn is true, it will do the CDN stuff
`	if options.Cdn {
		var err error
		scanner.cdn, err = cdncheck.NewWithCache()
		if err != nil {
			return nil, err
		}
	}`

**Comment by 003random** [comment]
While the actual check is not performed because that one uses options.EcludeCDN instead of options.Cdn
https://github.com/projectdiscovery/naabu/blob/master/v2/pkg/runner/runner.go#L234

**Comment by 003random** [comment]
Like i said earlier the naming is rather confusing and the bool flipping in various placings doesnt make it easier too https://github.com/projectdiscovery/naabu/issues/107#issuecomment-727678410

**Comment by 003random** [comment]
So in short. when not specifying the flag it creates the CDN client (which makes the GET requests) but does not do the actual check functions.
And then when actually specifying the flag, it does not create the CDN client but does do the check function which I reckon will fail due to the client not being initialized.
This can either be fixed by appending another ! at the start of the if statement on line 129 of scan.go, or by removing the ! on line 50 of runner.go
