### ISSUE TITLE
[feature] Add support for IPv4 and CIDR IP ranges and other features

### ISSUE THREAD

**Issue by bawzz234** [projectdiscovery/naabu#109]
Hello, 

Thanks for creating this app. I was actually looking for a GOlang's port scanner. Simply because of its excellent performance on threads and accuracy. And the speed is incomparable to other languages. 

It would be very useful if you could add these features:

- [x] Add support for ipv4 and CIDR Ranges. For example:
123.123.12.23-123.123.12.255
123.123.0.0/17

So the command may look like this for IPv4 Ranges:
**scanner.exe -threads=100 -protocol=tcp -host=123.123.12.23-123.123.12.255 -ports=8080,80,443**
and if CIDR used:
**scanner.exe -threads=500 -protocol=tcp -host=123.123.0.0/17 -ports=8080,80,443**
  if both type of ranges is not possible to add then IPv4 is most preferable.

- [x] Add function to save the open port results to a file (IP:Port) format.
For example, the command used:
**scanner.exe -threads=100 -protocol=tcp -host=123.123.12.23-123.123.12.255 -ports=8080,80,443 -output=result.txt**
if the open ports found from IPs they will be saved as IP:Port format. If multiple open ports found from same IP, then they will be added in new line like this:
123.123.12.132:80
123.123.12.132:8080

- [x] Have option to set ranges of ports. For example:
**-ports=443,80,8080,9000-10000**

- [x] Have option to select scan method. SYN Scan as default is most preferable. 
- [x] a custom -timeout= option 

Hope you could add this features. There are lots of other port scanners from different languages, but rarely on golang. These features will surely bring this go app to the top.

Best Regards

**Comment by bauthard** [comment]
Hi @bawzz234, 

Thank you for listing these feature requests, I'm not sure if you already use naabu or not, as all these features are already supported in naabu. 

> Add support for ipv4 and CIDR Ranges

You can already do this with `naabu -host 123.123.0.0/17`

>  Add function to save the open port results to a file (IP:Port) format.

This is the only and default format of the naabu output.

```bash
$ echo 1.1.1.1 | naabu -silent

1.1.1.1:53
1.1.1.1:80
1.1.1.1:443
```

>  Have option to set ranges of ports. For example:

Naabu supports the same format as `nmap`, so you can already use all type of input for ports as well. 

```
naabu -host 1.1.1.1 -ports 80
naabu -host 1.1.1.1 -ports 80-1000
naabu -host 1.1.1.1 -ports 80,443
```
You can use them all together as well.

>  Have option to select scan method. SYN Scan as default is most preferable.

This is default scan mode, if you running naabu with root user.

>  a custom -timeout= option

You already have `timeout` flag for this.

Closing this issue as there is nothing to add from our side, do let us know if you more inputs on this.
