### ISSUE TITLE
can't run naabu on mac with sudo

### ISSUE THREAD

**Issue by Arrnitage** [projectdiscovery/naabu#1092]
### Naabu version:

<img width="539" alt="image" src="https://github.com/projectdiscovery/naabu/assets/48816467/dcfbb943-5f7f-4ec9-a002-04c5e2f758a9">

### Current Behavior:

`sudo naabu -v`
<img width="1193" alt="image" src="https://github.com/projectdiscovery/naabu/assets/48816467/8f291958-4bd8-44c0-a13e-ce8750cdaa28">

**Comment by dogancanbakir** [comment]
I couldn't repro the issue. Is it possible that pcap dep is missing from the sys? See https://github.com/projectdiscovery/naabu?tab=readme-ov-file#prerequisite
```console
$ sudo ./naabu -host scanme.sh -v

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.3.1 (latest)
[INF] Running host discovery scan
[DBG] Received ICMP response from 128.199.158.128
[DBG] Received ICMP response from 128.199.158.128
[DBG] Received ICMP response from 128.199.158.128
[DBG] Received ICMP response from 128.199.158.128
...
```

**Comment by Arrnitage** [comment]
maybe , it is macOS problem. i can run naabu with low privilege user, but i can't run it with root. I don't know how to config macOS that can run naabu with root

**Comment by intbjw** [comment]
me too
`SIGSEGV: segmentation violation
PC=0x7ff82614c116 m=11 sigcode=1 addr=0x70
signal arrived during cgo execution

goroutine 35 gp=0xc0000b48c0 m=11 mp=0xc000900008 [syscall]:
runtime.cgocall(0x1073b80a0, 0xc000089988)
	runtime/cgocall.go:157 +0x4b fp=0xc000089960 sp=0xc000089928 pc=0x106630d0b
github.com/google/gopacket/pcap._Cfunc_pcap_datalink(0x0)
	_cgo_gotypes.go:353 +0x47 fp=0xc000089988 sp=0xc000089960 pc=0x106cbb7a7
github.com/projectdiscovery/naabu/v2/pkg/scan.TransportReadWorker.func2.(*Handle).LinkType.(*Handle).pcapDatalink.1(0x0?)
	github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:402 +0x3f fp=0xc0000899c8 sp=0xc000089988 pc=0x106ccb0df
github.com/google/gopacket/pcap.(*Handle).pcapDatalink(...)
	github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:402
github.com/google/gopacket/pcap.(*Handle).LinkType(...)
	github.com/google/gopacket@v1.1.19/pcap/pcap.go:592
github.com/projectdiscovery/naabu/v2/pkg/scan.TransportReadWorker.func2(0xc000052720, 0xc000dcd0a0?)
	github.com/projectdiscovery/naabu/v2/pkg/scan/scan_unix.go:628 +0x85 fp=0xc000089fc0 sp=0xc0000899c8 pc=0x106ccaba5
github.com/projectdiscovery/naabu/v2/pkg/scan.TransportReadWorker.gowrap1()
	github.com/projectdiscovery/naabu/v2/pkg/scan/scan_unix.go:673 +0x28 fp=0xc000089fe0 sp=0xc000089fc0 pc=0x106ccaae8
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000089fe8 sp=0xc000089fe0 pc=0x10669a7a1
created by github.com/projectdiscovery/naabu/v2/pkg/scan.TransportReadWorker in goroutine 50
	github.com/projectdiscovery/naabu/v2/pkg/scan/scan_unix.go:673 +0x77

goroutine 1 gp=0xc0000061c0 m=nil [runnable, locked to thread]:
regexp/syntax.(*parser).checkLimits(0xc000ef9c00?, 0xc0006cff10?)
	regexp/syntax/parse.go:161 +0x5f fp=0xc00087db50 sp=0xc00087db48 pc=0x106a15edf
regexp/syntax.(*parser).push(0xc000ef9c00, 0xc0006cff10)
	regexp/syntax/parse.go:327 +0x2e5 fp=0xc00087dba0 sp=0xc00087db50 pc=0x106a16885
regexp/syntax.(*parser).literal(0xc000ef9c00, 0x65)`
