### ISSUE TITLE
[Bug] Timeout error with CDN endpoints

### ISSUE THREAD

**Issue by jcalo-git** [projectdiscovery/naabu#110]
trying to scan a local subnet returns the following error with both normal and sudo privileges. here is the argument

sudo naabu -p - -host {IP.ADDRESS}

**Comment by bauthard** [comment]
Hi @jcalo-git, 

This bug is fixed in the master code at this commit https://github.com/projectdiscovery/naabu/commit/13251e1a871f607e6254853aa9db55242b9d8ef3, either you can build the binary from source or we are going to create release for naabu in coming week.

**Comment by jcalo-git** [comment]
Awesome thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
