### ISSUE TITLE
An error occurred during runtime

### ISSUE THREAD

**Issue by jiaocoll** [projectdiscovery/naabu#1122]
panic: runtime error: invalid memory address or nil pointer dereference
[worker 1   ] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe25485]
[worker 1   ] 
[worker 1   ] goroutine 45 [running]:
[worker 1   ] [github.com/projectdiscovery/naabu/v2/pkg/scan.(*Scanner).TCPResultWorker](http://github.com/projectdiscovery/naabu/v2/pkg/scan.(*Scanner).TCPResultWorker)(0xc00a503e60, {0x1bf9eb0, 0xc002d539f0})
[worker 1   ]   /home/ameng/桌面/naabu-v2.3.1/v2/pkg/scan/scan.go:282 +0x6c5
[worker 1   ] created by [github.com/projectdiscovery/naabu/v2/pkg/scan.(*Scanner).StartWorkers](http://github.com/projectdiscovery/naabu/v2/pkg/scan.(*Scanner).StartWorkers) in goroutine 36
[worker 1   ]   /home/ameng/桌面/naabu-v2.3.1/v2/pkg/scan/scan.go:194 +0xd1

code:
![image](https://github.com/projectdiscovery/naabu/assets/62785738/827892c3-9c2d-4295-b6af-7daadbc1a2a9)

If an error occurs here, should we first determine whether this variable is nil and determine the content of the variable

**Comment by Mzack9999** [comment]
@jiaocoll The `Phase` field should never be nil as it's initialized during the call to `Acquire(...)`. Would it be possible to provide all the info to reproduce the issue with the full stack trace?

**Comment by Mzack9999** [comment]
Not reproducible - Closing
