### ISSUE TITLE
Naabu outputs unrelated IP when it runs simultaneously with Nuclei

### ISSUE THREAD

**Issue by mhmmdazhari** [projectdiscovery/naabu#1149]
### Naabu version:
2.3.1

### Current Behavior: 
Naabu outputs some IPs that are unrelated to its scanned target. When I try to lookup this IP to hostname, it results in a subdomain belonging to a different company that I am currently scanning on Nuclei running on the same machine. I don't know why Nuclei Target could bother Naabu results when it runs simultaneously, but this would cause inaccurate results on Naabu.

### Expected Behavior:
Naabu should outputs IP/host that related to its scanned target only, not mixed with unrelated IP in its results.

### Steps To Reproduce:

1. Run 'nuclei -l companyA-subdomain-list' and wait until scan process started.
2. Run 'naabu -l companyB-subdomain-list -p -' in the same machine.
3. Naabu would outputs IP belonging to company A (scanned on Nuclei) amidst the supposed related targets.

### Anything else:

<img width="1512" alt="Screenshot 2024-07-18 at 2 35 39 PM" src="https://github.com/user-attachments/assets/26748b64-a78d-4921-9895-3c1fde10095b">

**Comment by Mzack9999** [comment]
@mhmmdazhari This is a valid bug, as a workaround for the time being you can use the connect scan mode

**Comment by Mzack9999** [comment]
Trying to reproduce this after some time, but it seems fixed in `dev` branch - Source filtering is performed at port level via EBPF filter and source ip with ipranger populated while adding targets.

I'm closing as not reproducible. Let us know if you are still facing the issue @mhmmdazhari and we will have another look, thanks!
