### ISSUE TITLE
Service Version Discovery "-sV" Has No Effect

### ISSUE THREAD

**Issue by BitTheByte** [projectdiscovery/naabu#1150]
### Naabu version:
```
2.3.1
```

### Current Behavior:
```
N/A
```

### Expected Behavior:
Nmap similar output e.g.
```json
{"host":"google.com","ip":"142.251.37.46","timestamp":"2024-07-19T12:08:08.016872298Z","port":80,"protocol":"tcp","tls":false, "version": "xxx", "product": "gws", "type": "http"}
```

### Steps To Reproduce:
```
$ echo google.com | naabu -json -sV -json | jq
```
```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/naabu/pull/670
- [ ] https://github.com/projectdiscovery/naabu/issues/813
```

**Comment by Mzack9999** [comment]
@BitTheByte Service discovery is not yet implemented, I created another issue to provide better information about the existing flags. The functionality will be implemented in the future. I'm closing the issue as we will we working on https://github.com/projectdiscovery/naabu/issues and the functionality will be revisited later. Thanks!
