### ISSUE TITLE
Not able to install Naabu on Sequoia

### ISSUE THREAD

**Issue by JohnWongCHN** [projectdiscovery/naabu#1213]
MacOS: Sequoia 15.0
Go: 1.23.1

Try to install Naabu but got this error
```
...
golang.org/x/net/ipv4
golang.org/x/net/ipv6
github.com/google/gopacket/layers
golang.org/x/net/icmp
github.com/projectdiscovery/naabu/pkg/scan
github.com/projectdiscovery/naabu/pkg/runner
github.com/projectdiscovery/naabu/cmd/naabu
# github.com/projectdiscovery/naabu/cmd/naabu
link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
```

**Comment by akroidankur** [comment]
┌──(akroid㉿akroid)-[~]
└─$ go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.


not able to installl

**Comment by dogancanbakir** [comment]
@JohnWongCHN Could you retry with golang 1.21?

@akroidankur see https://github.com/projectdiscovery/naabu?tab=readme-ov-file#prerequisite

**Comment by JohnWongCHN** [comment]
I used golang 1.22.8 to successfully install Naabu, but after installation, I realized that I had used the wrong [documentation](https://docs.projectdiscovery.io/tools/naabu/install). I had installed the V1 version of Naabu.

There is no problem to use golang 1.23.2 on Sequoia to install Naabu V2. So close this issue🙂
