### ISSUE TITLE
how to understand -scan-all-ips

### ISSUE THREAD

**Issue by littleheary** [projectdiscovery/naabu#122]
i don't know how to understand -scan-all-ips,how to use this ?

**Comment by bauthard** [comment]
Hi @littleheary, 

```
host hackerone.com
hackerone.com has address 104.16.99.52
hackerone.com has address 104.16.100.52
```

If you notice, hackerone.com have 2 A record and similarly others domain/subdomains can have multiple `A` records, as default **naabu** perform a port scan on 1st IP, when `-scan-all-ips` flag is used, all the IP's will scanned for requested ports.
