### ISSUE TITLE
[Issue] Error handling timeout error when "no IP addresses found for host"

### ISSUE THREAD

**Issue by i-sylar** [projectdiscovery/naabu#123]
When i do a scan for a domain that throws in a "_**no IP addresses found for host**_" on my ubuntu workstation, i immediately get an error "_**[FTL] Could not run enumeration: No targets specified**_" which is fine. However, running the same command on my digital ocean droplets leaves it hanging at the "**_no IP addresses found for host_**" till i kill the script/command. Any work around for this or reason why?

PS a sample command is 
**_sudo naabu -p - -host watch.pubgesports.com -v -timeout 2000_**

**Comment by bauthard** [comment]
Hey @i-sylar, 

```bash
host watch.pubgesports.com
Host watch.pubgesports.com not found: 3(NXDOMAIN)
```

`watch.pubgesports.com` doesn’t have any record associated with it to scan for, can you run the above command on the box from where it's getting scanned and share the output?

**Comment by i-sylar** [comment]
seems to be an issue with the latest version 2.0.3. 2.0.2 seems to handle this error well. Here is a screenshot of both outputs

![2 0 2](https://user-images.githubusercontent.com/16762227/102757238-11e59480-4382-11eb-98e3-bd8860b2cbc2.png)
![2 0 3](https://user-images.githubusercontent.com/16762227/102757257-19a53900-4382-11eb-842a-c814875abeb1.png)

**Comment by i-sylar** [comment]
As visible, nxrecord lookup didnt return any valid response. Version 2.0.2 handled this error by giving the **_no target specified_**. Version 2.0.3 on the other hand freezes at the "**_no ip address found_**" and does not terminate execution.

Hope this helps.

**Comment by bauthard** [comment]
Thank you @i-sylar for sharing additional context, I can confirm it's a valid bug and timeout issue when IP is not found.

**Comment by i-sylar** [comment]
Thanks for the response. Great tool btw.
