### ISSUE TITLE
fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by z3dc0ps** [projectdiscovery/naabu#125]
fatal error: pcap.h: No such file or directory

Go verion : go version go1.15.5 linux/amd64

![1](https://user-images.githubusercontent.com/61974788/103164525-77c69600-4832-11eb-8846-5b5a849d1ba3.PNG)

**Comment by bauthard** [comment]
@z3dc0ps you need to install `apt install -y libpcap-dev` before installing naabu, will update the readme as well.

**Comment by z3dc0ps** [comment]
@bauthard Thank you, Now it's working , please update README also.

**Comment by PlayerX-SyntaX** [comment]
The following packages have unmet dependencies:
 libpcap0.8-dev : Depends: libpcap0.8 (= 1.10.0-2) but 1.10.1-4~bpo11+1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by mahfuz0712** [comment]
The following packages have unmet dependencies:
 libpcap0.8-dev : Depends: libpcap0.8 (= 1.10.0-2) but 1.10.1-4~bpo11+1 is to be installed
E: Unable to correct problems, you have held broken packages.
