### ISSUE TITLE
naabu: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by badboycxcc** [projectdiscovery/naabu#1251]
### Naabu version:
Naabu: 2.3.1. 
Uname -a. 
```
Linu 5.4.17-2136.328.3.el7uek.x86_64 #2 SMP Thu Jan 18 16:01:09 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Current Behavior:
```
naabu: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
```

### Expected Behavior:
Scan Ports

### Steps To Reproduce:
```
./naabu
```

**Comment by badboycxcc** [comment]
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by dogancanbakir** [comment]
@badboycxcc , see
https://github.com/projectdiscovery/naabu#prerequisite
https://github.com/projectdiscovery/naabu/discussions/139
https://github.com/projectdiscovery/naabu/issues/660
