### ISSUE TITLE
Where is Thread Command?

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/naabu#127]
hello. thank you for this project.. On main page, it says that thread can be used with the -c parameter.. but now I have seen that although I have just installed the naaubu program, the -c parameter does not exist in the terminal. How do I determine the thread count?

**Comment by bauthard** [comment]
@Phoenix1112 Not sure what exactly you mean, but it works here, Can you make sure you are the latest version?

```
echo 1.1.1.1 | naabu -c 10

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running SYN scan with root privileges
[INF] Found 3 ports on host 1.1.1.1 (1.1.1.1)
1.1.1.1:443
1.1.1.1:53
1.1.1.1:80
```

**Comment by Phoenix1112** [comment]
thanks for answer.I installed naabu with this command yesterday >> ```GO111MODULE = on go get -v github.com/projectdiscovery/naabu/v2/cmd/naab```

but I saw that v2.0.2 version is now installed. Now I downloaded the naabu latest version file from the releases section. now when I try again, the -c parameter now appears and works. Thank you for your wonderful projects.

**Comment by bauthard** [comment]
thank you for the feedback and for confirming this.
