### ISSUE TITLE
unable to find pcap package, unable to install

### ISSUE THREAD

**Issue by saikiran7022** [projectdiscovery/naabu#130]
installing through go:
GO111MODULE=on go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu

error:-
go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

Unable to install

![error](https://user-images.githubusercontent.com/42044377/106347624-379d7c00-62e6-11eb-8719-f0035caebbec.png)
![er2](https://user-images.githubusercontent.com/42044377/106347632-56037780-62e6-11eb-8664-5fb0a9c6c20b.png)

**Comment by bauthard** [comment]
@saikiran7022 make sure to install `libpcap-dev`, for example `apt install -y libpcap-dev` before installing naabu.
