### ISSUE TITLE
error in go build

### ISSUE THREAD

**Issue by learn-alam** [projectdiscovery/naabu#132]
when i run go build command in /naabu/v2/cmd/naabu directory following error occurs

# github.com/google/gopacket/pcap
/home/alam/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by bauthard** [comment]
@learn-alam `apt install -y libpcap-dev`, I've updated the readme as well.

**Comment by learn-alam** [comment]
Thanks for your help.
Issue is fixed.
