### ISSUE TITLE
Not scanning hosts when subdomain is number

### ISSUE THREAD

**Issue by scriptshuva** [projectdiscovery/naabu#133]
**Describe the bug**
Not scanning hosts when subdomain is number

**To Reproduce**
naabu -host 20.example.com -p 1-100

**Tested device**
Tested macOS/Windows/Linux

**Comment by ehsandeep** [comment]
@scriptshuva `20.example.com` is not a valid host, do you have an active host example to share for this?

**Comment by scriptshuva** [comment]
Oh. Sorry I forget to check this. 

It's possible to scanning false positive subdomain list using naabu? I tried scanning subdomain list. :-)

Thanks,

**Comment by ehsandeep** [comment]
Hey, surely feed the passive/invalid subdomains to naabu, and it will filter out invalid ones and you will see results for host with the valid record, you can filter the valid results of subdomains using [dnsx](https://github.com/projectdiscovery/dnsx) before passing the results to naabu. 

```
cat subdomains.txt | dnsx | naabu 
```
or
```
subfinder -d example.com | dnsx | naabu 
```
