### ISSUE TITLE
[Bug] work/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by zealsham** [projectdiscovery/naabu#138]
**Describe the bug**
i keep getting this error when i try to install naabu on my vps work/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory

**Comment by ehsandeep** [comment]
@zealsham, you need to install `apt install -y libpcap-dev` before installing naabu.
