### ISSUE TITLE
How can I pass the naabu output to nmap for version detection?

### ISSUE THREAD

**Issue by dark-warlord14** [projectdiscovery/naabu#14]
Any help is appreciated

**Comment by arbazkiraak** [comment]
@dark-warlord14 

This might help! 

https://github.com/Ullaakut/nmap

**Comment by Mzack9999** [comment]
@dark-warlord14 I think you can use something like this to execute nmap:

```shell
$ echo 192.168.1.1 | naabu -silent | awk -F ':' '{system("nmap -p "$2" "$1)}'
Starting Nmap 7.60 ( https://nmap.org ) at 2020-06-04 01:02 CEST
Nmap scan report for _gateway (192.168.1.1)
Host is up (0.00042s latency).

PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 0.15 seconds
Starting Nmap 7.60 ( https://nmap.org ) at 2020-06-04 01:02 CEST
Nmap scan report for _gateway (192.168.1.1)
Host is up (0.00046s latency).

PORT   STATE SERVICE
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 0.09 seconds
```

or this to prepare the nmap statements
```shell
$ echo 192.168.1.1 | naabu -silent | awk -F ':' '{print "nmap -p " $2 " " $1}'
nmap -p 22 192.168.1.1
nmap -p 80 192.168.1.1
```

**Comment by dark-warlord14** [comment]
@Mzack9999 This looks pretty neat. Thank you. I will try this.

I have one question though. 
Wouldn't it slow down the process when I have around 1K ip address that I want to scan?

**Comment by bauthard** [comment]
Hi @dark-warlord14, 

> Wouldn't it slow down the process when I have around 1K ip address that I want to scan?

As `nmap` is another program you are going to run, the timing will surely increase depending on the `nmap` which is something we can not control from our side, as this issue is solved, I'm closing this thread now. 

I will update the running `nmap` with naabu details in the readme file for everyone.
