### ISSUE TITLE
checksum error aborts installation and/or update.

### ISSUE THREAD

**Issue by unstabl3** [projectdiscovery/naabu#155]
**Describe the bug**
Hi :)
I normally use the -u flag to update/install the go tools.
during the update, I found there is a mismatch in the checksum for  github.com/projectdiscovery/mapcidr@v0.0.5:

**To Reproduce**

machine ubuntu 18.04
GO111MODULE=on go get -u -v github.com/projectdiscovery/naabu/v2/cmd/naabu

**Screenshots**
![Screenshot 2021-04-01 132342](https://user-images.githubusercontent.com/48474764/113261796-81f2a780-92ed-11eb-9522-72a04462f954.jpg)

The end result is I cannot install or update the tool. :(

Thanks,
shubham

**Comment by ehsandeep** [comment]
@unstabl3 avoid using `-u` flag while installing or updating tools as `-u` flag attempt to download the latest version of modules defined under `go.sum` file vs what is the intended version of the module to use.

You can install or update the project using:- 

```
GO111MODULE=on go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
```

**Comment by ehsandeep** [comment]
Closing as this is not an issue.
