### ISSUE TITLE
[Bug] Naabu leaks temporary files, eventually rendering system inoperable

### ISSUE THREAD

**Issue by iangcarroll** [projectdiscovery/naabu#158]
**Describe the bug**
Naabu does not delete files it creates when preparing targets in [`Runner.mergeToFile()`](https://github.com/projectdiscovery/naabu/blob/8101bb9050e418165c0ab3061a2ed3f6d9701f2c/v2/pkg/runner/targets.go#L37). It is supposed to be deleted on [`Runner.Close`](https://github.com/projectdiscovery/naabu/blob/8101bb9050e418165c0ab3061a2ed3f6d9701f2c/v2/pkg/runner/runner.go#L207), but this function is never called.

The end result (if persistently running Naabu) is that certain Linux boxes will never boot again without manual recovery, because [Systemd cannot handle](https://serverfault.com/questions/987488/boot-stuck-at-a-start-job-is-running-for-create-volatile-files-and-directories) significant amounts of temporary files on a boot.

I do not think a file is really needed here at all (and does not seem to need to be retained past the mergeToFile call), but maybe I am missing something.

**Comment by iangcarroll** [comment]
It appears this is exacerbated by Naabu calling into `projectdiscovery/hmap` and also creating an entirely new LevelDB database on each execution as well. Calling `Runner.Close` would fix both of these things, I believe.

**Comment by ehsandeep** [comment]
thank you for reporting this @iangcarroll, you are right, it's a known issue that we will be addressing in the next release.

**Comment by ehsandeep** [comment]
@iangcarroll this is now fixed in the development version with the following PR https://github.com/projectdiscovery/naabu/pull/160
