### ISSUE TITLE
Is it printed of filterd port as well?

### ISSUE THREAD

**Issue by ice-doom** [projectdiscovery/naabu#159]
When use the nmap scan of filterd status, the port is actually open in sometimes

**Comment by ehsandeep** [comment]
@ice-doom, it should only print OPEN ports, do you have an example to share?

**Comment by ice-doom** [comment]
![image](https://user-images.githubusercontent.com/25363717/114358856-fbb84a00-9ba5-11eb-850a-5be6acc24d5a.png)
![image](https://user-images.githubusercontent.com/25363717/114358966-18548200-9ba6-11eb-9352-d1011f985180.png)

**Comment by ehsandeep** [comment]
it looks like an OPEN port to me as it's running an HTTP web server on port 80, not sure how nmap categorizing filtered state, anyway if you using `nmap` support in naabu, you will see what nmap split out, we don't control/alter that part.

closing this issue as this is not specific to naabu.
