### ISSUE TITLE
[Bug] Could not create runner:

### ISSUE THREAD

**Issue by zhegege** [projectdiscovery/naabu#161]
Because in version 2.0.3, the program will not stop automatically when I encounter a domain name that cannot be resolved, so I can only use the old version 2.0.2. But in 2.0.2, I encounter a new problem

Could not create runner: Get "https://www.cloudflare.com/ips-v4": read tcp 192.168.43.254:36923->104.16.124.96:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by ehsandeep** [comment]
@zhegege this looks duplicate of https://github.com/projectdiscovery/naabu/issues/123 and fixed already, we will create a new release soon.

**Comment by zhegege** [comment]
ok thinks ，it a good tools
