### ISSUE TITLE
[Bug] Could not get IP for host

### ISSUE THREAD

**Issue by divyansh2401** [projectdiscovery/naabu#162]
Whenever I run naabu 
naabu -host hackerone.com -v

I got the this:
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.3

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[WRN] Could not read configuration file /home/osboxes/.config/naabu/naabu.conf: EOF
[INF] Running CONNECT scan with non root privileges
[WRN] Could not get IP for host: hackerone.com
[WRN] read udp 192.168.84.140:42127->8.8.4.4:53: i/o timeout

**Comment by ehsandeep** [comment]
@divyansh2401 `Could not read configuration file /home/osboxes/.config/naabu/naabu.conf: EOF` this is not an issue/error but a warning, as default the config file is commented out, you need to remove the comments if you wanted to use it, so that's not an issue.

**Comment by ehsandeep** [comment]
I'm running same scan on mac and it works.

```
naabu -host hackerone.com -v

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] Could not read configuration file /Users/ehsandeep/.config/naabu/naabu.conf: EOF
[INF] Running CONNECT scan with non root privileges
[DBG] Using host 104.16.100.52 for enumeration
[INF] Found 5 ports on host hackerone.com (104.16.100.52)
hackerone.com:443
hackerone.com:8443
hackerone.com:8080
hackerone.com:25
hackerone.com:80
```

**Comment by realArcherL** [comment]
For some reason, I am facing the same issue, but its only on Kali Linux, may be something related to Kali.

**Comment by sirmalware** [comment]
I'm  using ubuntu and getting the same issue. maybe its something linux related.
