### ISSUE TITLE
# github.com/google/gopacket/pcap - Installation error

### ISSUE THREAD

**Issue by chevonmdphillip** [projectdiscovery/naabu#163]
# github.com/google/gopacket/pcap
../pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.

**Comment by ehsandeep** [comment]
@chevonmdphillip you need to install `apt install -y libpcap-dev` as listed in the readme.

**Comment by chevonmdphillip** [comment]
Worked like a charm. In my case it was `sudo yum install -y libpcap-devel`. I'm closing this one out.
