### ISSUE TITLE
Add verbose 

### ISSUE THREAD

**Issue by obreinx** [projectdiscovery/naabu#164]
Add verbose feature so we can see whats happening with the targets 
Thanks <3

**Comment by ehsandeep** [comment]
@obreinx naabu already have `-v` and `-debug` flag support, what exactly you looking for?

**Comment by obreinx** [comment]
my bad i didn't saw them ,
anyway thanks for this real cool project <3

**Comment by ehsandeep** [comment]
np, thank you
