### ISSUE TITLE
Install error on 32bit linux

### ISSUE THREAD

**Issue by hahwul** [projectdiscovery/naabu#17]
I have naabu installation error on a 32bit pc. My guess is 32/64 bit difference. Is there a solution?

Error log
```
$ go get -v github.com/projectdiscovery/naabu/cmd/naabu
github.com/projectdiscovery/naabu/pkg/scan
# github.com/projectdiscovery/naabu/pkg/scan
../../go/src/github.com/projectdiscovery/naabu/pkg/scan/scan.go:143:36: constant 8999999999 overflows int
```

ENV
```
- Ubuntu 18.04.4 LTS (kernel 4.15.0-88-generic)
- 32bit computer
- installed libpcap-dev
```

**Comment by hahwul** [comment]
First, i temporarily adjusted the value of the `rand.Intn` and installed it.
(Is int size different per OS bit in golang..?........)

```
130         // Construct all the network layers we need.
131         ip4 := layers.IPv4{
132                 SrcIP:    s.srcIP,
133                 DstIP:    s.host,
134                 Version:  4,
135                 TTL:      255,
136                 Protocol: layers.IPProtocolTCP,
137         }
138         tcpOption := layers.TCPOption{
139                 OptionType:   layers.TCPOptionKindMSS,
140                 OptionLength: 4,
141                 OptionData:   []byte{0x12, 0x34},
142         }
143         randSeq := 1000000000 + rand.Intn(89999)
144
```

**Comment by Ice3man543** [comment]
Hi @hahwul, thanks for creating this issue. This seems like something we need to investigate. We'll check this out and let you know!

**Comment by hahwul** [comment]
@Ice3man543 
Thank you! If you need any information, please mention me :D

**Comment by Mzack9999** [comment]
@hahwul This is definitely an issue related to the maximum interger size between x86 and x86_64 architecture as indeed they require a different memory allocation. We will address this shortly, thank you very much for reporting the issue!

**Comment by Ice3man543** [comment]
@hahwul this should be fixed in the latest release. Thanks for reporting this issue!

**Comment by parthmalhotra** [comment]
Latest version not working on 32 bit @Ice3man543
