### ISSUE TITLE
Scan fails on Virtual Interfaces as MAC is not defined

### ISSUE THREAD

**Issue by Penjo** [projectdiscovery/naabu#18]
![Screenshot_36](https://user-images.githubusercontent.com/9008132/76537522-7947ed00-64b0-11ea-9003-4a4e655e3c69.png)
failed when install
my os ubuntu 18.04

anyone can help?

**Comment by bauthard** [comment]
This doesn't look like an error to me @penjo, did you tried to run `naabu -h` after this?

**Comment by Penjo** [comment]
![Screenshot_37](https://user-images.githubusercontent.com/9008132/76591274-74bc1c80-6522-11ea-809a-b2e932350a70.png)
always show `Host seems down`

**Comment by bauthard** [comment]
Hi @Penjo, 

Please always try to include all possible information if you want us to identify the problem, Can you include the output of the below?

`naabu -host hackerone.com -v` 

and 

`curl -sI hackerone.com`

**Comment by Penjo** [comment]
hi @bauthard 
![Screenshot_38](https://user-images.githubusercontent.com/9008132/76623673-81fafa80-6566-11ea-8826-45bf99836e6e.png)

**Comment by bauthard** [comment]
This is odd, but just to confirm what `machine`, `naabu -v` and I can see but still you running it as root?

**Comment by Penjo** [comment]
hi @bauthard 
ubuntu 18.04
![Screenshot_39](https://user-images.githubusercontent.com/9008132/76624412-d652aa00-6567-11ea-8a0f-701e8b99e32e.png)

**Comment by bauthard** [comment]
Thank you, let's find the root cause of this! 

also `naabu -version` and `ifconfig` in case this is related to an interface issue. 

Did you tried running `nmap` on this box? if so that also not working?

**Comment by Penjo** [comment]
nmap looks normal @bauthard 
![Screenshot_40](https://user-images.githubusercontent.com/9008132/76625541-0c912900-656a-11ea-91ca-4e9d76c11da5.png)
![Screenshot_41](https://user-images.githubusercontent.com/9008132/76625548-1155dd00-656a-11ea-9c26-4d0e2783797d.png)
![Screenshot_42](https://user-images.githubusercontent.com/9008132/76625553-14e96400-656a-11ea-8fa8-c6bf14af4539.png)

**Comment by Mzack9999** [comment]
@Penjo thanks for reporting this. The issue appears to be that your `venet0` interface doesn't have a physical MAC address defined. Usually this happens on virtual interfaces and it creates problems while using PCAP as the source MAC is needed to forge the packet to send to the external network gateway. Actually I don't recall if the `--verify` options operates a full connect scan or just handle the result of the first SYN scan, in the first case it would bypass the need of MAC as it operates at socket level and leave this part of the network stack handled by the linux kernel. We will address this as soon as possible. Again, thanks for reporting the issue and for your interest in the tool!

**Comment by Ice3man543** [comment]
> On virtual network interfaces the scan needs to be performed at socket level as routing and hardware layer are already handled by the linux kernel

**Comment by Mayur1995** [comment]
FYI.

Facing the same issue while running on a local VM. Nmap seems to be working fine but naabu is failing to scan the host with the above message.
