### ISSUE TITLE
Support WSL

### ISSUE THREAD

**Issue by dody2004** [projectdiscovery/naabu#183]
i hope naabu support wsl as soon as possible 
thanks

**Comment by dody2004** [comment]
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using host yahoo.com for enumeration
[INF] Starting scan on host yahoo.com (74.6.143.25)

**Comment by ehsandeep** [comment]
@dody2004 **naabu** runs on Windows systems, can you share few points on how it will be more useful with WSL support or in what cases the current OS support doesn't fit/works well?
