### ISSUE TITLE
[Bug]  host does not exist

### ISSUE THREAD

**Issue by w4cky** [projectdiscovery/naabu#192]
**Describe the bug**
host does not exist and naabu it does not detect it

**To Reproduce**
# naabu -host ksfkdskfdgfkdsgfdsagfsagkf.com -top-ports 1000 -ping -debug -nmap     

Why doesn't naabu say after a few seconds that the host doesn't exist? Only waiting forever? I would like naabu to shut down after a few seconds when the host does not exist.

**Comment by ehsandeep** [comment]
@w4cky what `naabu -version` says?

**Comment by w4cky** [comment]
naabu -version

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.3

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 2.0.3

**Comment by ehsandeep** [comment]
@w4cky latest version is [v2.0.4](https://github.com/projectdiscovery/naabu/releases/tag/v2.0.4) which also includes a fix for the issue that existed in previous versions.

**Comment by w4cky** [comment]
thx
