### ISSUE TITLE
CDN Ips Issue

### ISSUE THREAD

**Issue by jaikishantulswani** [projectdiscovery/naabu#193]
@ehsandeep suddenly naabu throwing error regarding cdn ips like 
`Could not create runner: Get "https://cdn.projectdiscovery.io/cdn/cdn-ips": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` when using **-exclude-cdn** flag
may be this is due to the link https://cdn.projectdiscovery.io/cdn/cdn-ips is not reachable

**Comment by ehsandeep** [comment]
thanks for reporting, on it.

**Comment by ehsandeep** [comment]
should be working fine now, thanks again for reporting.

**Comment by Akshat-Pathak** [comment]
still not working

**Comment by ehsandeep** [comment]
@Akshat-Pathak you need to update naabu to avoid this issue.
