### ISSUE TITLE
[Bug]  Issues with printing results 

### ISSUE THREAD

**Issue by avi7167** [projectdiscovery/naabu#194]
**Description**

**command used to install naabu :** GO111MODULE=on go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu

on using naabu to find  http servers, the command takes time to run but does not print out results.
prerequisites for naabu are installed i.e. libpcap-dev 
**command :** cat subs.txt | naabu -silent | naabu -silent | tee probed.txt

**Comment by ehsandeep** [comment]
```
cat subs.txt | naabu -silent | naabu -silent | tee probed.txt
```

Not sure why you used `naabu` twice, also do you example input to share so we can look into it?

**Comment by avi7167** [comment]
As stated in README.md :
the ports discovered can be piped to other tools too. for example, you can pipe the ports discovered by naabu to naabu which will then find running http servers on the host.

echo hackerone.com | naabu -silent | naabu -silent

http://hackerone.com:8443
http://hackerone.com:443
http://hackerone.com:8080
http://hackerone.com:80

       While reading naabu usage I came at this point, tried to implement it. Please do correct me if I'm going out of point.

**Comment by Mzack9999** [comment]
Nice catch @avi7167 ! I think there is a mistake in the `README.md` and it should have been `echo hackerone.com | naabu -silent | httpx -silent`. Naabu accepts fqdn, ip, and cidr as input, whereas ports are provided through the `-p` command-line option. We are going to correct the readme.

**Comment by avi7167** [comment]
Thank you @ehsandeep @Mzack9999 for your kind support.
