### ISSUE TITLE
Runner doesn't have any output

### ISSUE THREAD

**Issue by namm2** [projectdiscovery/naabu#196]
Hi, I'd like to embed naabu into my toy tool, not sure if I did it incorrectly but I can't get output of the runner results

```go
import (
    "log"
    "github.com/projectdiscovery/naabu/v2/pkg/runner"
)

func main() {
    options := runner.Options{
      JSON: true,
      Verbose: true,
      Debug: true,
      Threads: 25,
      Retries: 1,
      Rate: 2000,
      Ping: true,
      ExcludeCDN: true,
      EnableProgressBar: true,
      ScanType: "s",
      Host: "scanme.nmap.org",
      Output: "/tmp/naabu_output.txt",
    }

    r, err := runner.NewRunner(&options)
    if err != nil {
      log.Println(err)
    }
    err = r.RunEnumeration()
    if err != nil {
      log.Println(err)
    }
}
```

```go run main.go``` shows scanning progress, but there's no results afterwards.

I intent to capture the results and throw it around, how can I achieve it? Thanksk.

**Comment by namm2** [comment]
It looks like `unprivileged: true` doesn't work. After `go build main.go` and ran `sudo ./main`, the results are printed to output.

**Comment by namm2** [comment]
Solution is to build docker image then run it with capabilities NET_CAP_RAW,  NET_CAP_BIND_SERVICE https://unix.stackexchange.com/questions/389879/how-to-set-capabilities-with-setcap-command

**Comment by ehsandeep** [comment]
@namm2 `unprivileged: true` looks like you using an older version? as this flag is not part of the latest release, also naabu supports two types of scan, **CONNECT** (doesn't require root and slow), **SYN** (requires root + fast).

Running SYN scan with root privilege is advisable to use for best performance.

**Comment by Done461** [comment]
still not working with null results even with sudo command 
![image](https://user-images.githubusercontent.com/52113967/233458569-3f618f50-d291-4feb-b8a4-6761d713fc12.png)

**Comment by ehsandeep** [comment]
@Done461 latet version of naabu is 2.1.5

**Comment by Done461** [comment]
> @Done461 latet version of naabu is 2.1.5

any idea how to update it ?

**Comment by ehsandeep** [comment]
> > @Done461 latet version of naabu is 2.1.5
> 
> any idea how to update it ?

https://github.com/projectdiscovery/pdtm
