### ISSUE TITLE
[Feature Request] Reducing false negative through ICMP Echo Request

### ISSUE THREAD

**Issue by galimba** [projectdiscovery/naabu#2]
A lot of boxes will not respond to a SYN scan. Including an ICMP echo request along with the port sweep would significantly reduce the amount of targets classified to be offline.

**Comment by bsysop** [comment]
Would be great a stealth/passive/aggressive arg option

**Comment by Mzack9999** [comment]
@galimba if I understood correctly would you like to see implemented the same host discovery strategy of nmap?

As I know these are the default probes that are executed by nmap:

* ICMP echo request
* TCP SYN packet to port 443
* TCP ACK packet to port 80
* ICMP timestamp request

**Comment by galimba** [comment]
I'm not saying to copy nmap, I'm sure that's not the intent of naabu. as the readme says "allows you to enumerate valid ports for hosts in a fast and reliable manner".
The issue is that it is not reliable if there's a considerable chance that the host is up, but not responding to SYN scans.
If naabu gets no SYN/ACK from a SYN, it assumes the host is down. In order to mitigate this scenario, a user would have to ping every host that showed as being down to see if perhaps they were up.
So I'm proposing to include an optional ICMP echo request, basically a ping within naabu, as an aditional check for those hosts.
Granted, it could also be that a host is blocking SYN scans AND also not responding ICMP echo requests, but in that case you definitely need nmap or some other form of advanced port scan.

I don't think there's a need for a timestamp request in this scenario.

**Comment by bauthard** [comment]
Hey @galimba,
I think this would be doable. We'll be working on this issue. Thanks for notifying!

**Comment by Ice3man543** [comment]
Hi @galimba, i just added a `Pn` flag to do a simple ICMP echo request on the hosts. This serves two benefits - 

1. We find if the host is actually alive and not accepting SYN probes.
2. We do latency calculation on all ips if a domain has been supplied and the fastest IP is used for enumeration.

We don't really care about much in-depth validation. As you said, something like nmap could be easily used in such cases. Thanks!
