### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by sumgr0** [projectdiscovery/naabu#22]
# github.com/google/gopacket/pcap
/root/go/src/github.com/google/gopacket/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.

Looks like the pcap package is no longer available the google repo

**Comment by sumgr0** [comment]
Resolved

**Comment by sawmj** [comment]
for whoever stumbled upon the same issue
you need to install the pcap library

`sudo apt-get install libpcap-dev`
