### ISSUE TITLE
[Bug] Windows system always show non root privileges

### ISSUE THREAD

**Issue by LywLover** [projectdiscovery/naabu#228]
**Describe the bug**
I run is as administrator on windows system but always got "Running CONNECT scan with non root privileges".

After read the source code I found this function.
https://github.com/projectdiscovery/naabu/blob/b6bca90820180d35fab501038719682079b761a8/v2/pkg/runner/util.go#L13-L15

Getuid returns the numeric user id of the caller, but on Windows, it returns -1 .

**Comment by ehsandeep** [comment]
@LywLover Yes, this is expected, on windows connect scan is the only option to use.
