### ISSUE TITLE
Naabu not Scanning ports.

### ISSUE THREAD

**Issue by KathanP19** [projectdiscovery/naabu#23]
natsu@DESKTOP-T32LAE7:~/go/bin$ sudo ./naabu -host hackerone.com

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v1

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using host hackerone.com for enumeration
[INF] Starting scan on host hackerone.com (104.16.99.52)
natsu@DESKTOP-T32LAE7:~/go/bin$

**Comment by bauthard** [comment]
Are you running this on windows?

**Comment by bauthard** [comment]
FYI it's known issue if you trying to run this on windows, please check https://github.com/projectdiscovery/naabu/issues/7

**Comment by KathanP19** [comment]
i tried it in wsl kali

**Comment by bauthard** [comment]
Thanks for information @KathanP19, closing this as duplicate https://github.com/projectdiscovery/naabu/issues/7, for now please use docker.
