### ISSUE TITLE
mac m1 内存错误

### ISSUE THREAD

**Issue by linuxdy** [projectdiscovery/naabu#235]
____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.3

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x43bacf4]

goroutine 1 [running]:
github.com/projectdiscovery/mapcidr.AddressCountIpnet(0xc00003baa0)
	/Users/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v0.0.8/cidr.go:47 +0x14
github.com/projectdiscovery/ipranger.(*IPRanger).add(0xc0000920f0, {0xc00003baa0, 0x12})
	/Users/runner/go/pkg/mod/github.com/projectdiscovery/ipranger@v0.0.3-0.20210831161617-ac80efae0961/ipranger.go:77 +0x67
github.com/projectdiscovery/ipranger.(*IPRanger).Add(0xc0000920f0, {0xc00003baa0, 0x12})
	/Users/runner/go/pkg/mod/github.com/projectdiscovery/ipranger@v0.0.3-0.20210831161617-ac80efae0961/ipranger.go:65 +0x107
github.com/projectdiscovery/ipranger.(*IPRanger).AddHostWithMetadata(0xc0000920f0, {0xc00003baa0, 0x12}, {0x4610170, 0x0})
	/Users/runner/go/pkg/mod/github.com/projectdiscovery/ipranger@v0.0.3-0.20210831161617-ac80efae0961/ipranger.go:122 +0xc5
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).AddTarget(0xc000139440, {0xc00003baa0, 0x1000})
	/Users/runner/work/naabu/naabu/v2/pkg/runner/targets.go:110 +0xdb
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).PreProcessTargets.func1(0xc00015c600, 0xc0000f1aca, {0xc00003baa0, 0xc0000b3c18})
	/Users/runner/work/naabu/naabu/v2/pkg/runner/targets.go:90 +0x79
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).PreProcessTargets(0xc000139440)
	/Users/runner/work/naabu/naabu/v2/pkg/runner/targets.go:93 +0x1e5
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).Load(0xc000139440)
	/Users/runner/work/naabu/naabu/v2/pkg/runner/targets.go:29 +0x7a
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc000139440)
	/Users/runner/work/naabu/naabu/v2/pkg/runner/runner.go:118 +0x1fa
main.main()
	/Users/runner/work/naabu/naabu/v2/cmd/naabu/main.go:18 +0x15d

**Comment by forgedhallpass** [comment]
Duplicates #191
