### ISSUE TITLE
bypass redundant DNS lookups

### ISSUE THREAD

**Issue by PR3R00T** [projectdiscovery/naabu#251]
Have a flag in naabu that when you parse dnsx -resp output (subdomain [IP]) in it will skip DNS lookups of the subdomains again and then print out the Subdomain:port sockets like normal. Skips a second DNS lookup if you have chained these tools together.

**Comment by Mzack9999** [comment]
Implemented in https://github.com/projectdiscovery/tinydns/pull/4 via tinydns

**Comment by ehsandeep** [comment]
I can confirm the proposed solution works very well and can be extended to support all the pd tools involving active DNS resolution and will be published as an independent project at https://github.com/projectdiscovery/pdmesh, Internal GH issue to track https://github.com/projectdiscovery/team-backlogs/issues/154
