### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by GH846** [projectdiscovery/naabu#255]
Hi,

got an error trying to install latest version:

github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by ehsandeep** [comment]
@GH846 see multiple closed issues on same with details to fix - https://github.com/projectdiscovery/naabu/issues/130

**Comment by GH846** [comment]
@ehsandeep aaargh... sorry about that ....  thanks a lot
