### ISSUE TITLE
i have problem when run 

### ISSUE THREAD

**Issue by shadihh9** [projectdiscovery/naabu#28]
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[FTL] Program exiting: no input list provided
naabu -ports full-exclude-ports 80,443 -hL /root/Desktop/recon/xxx/exmple -o exmport.txt

**Comment by bauthard** [comment]
Hi @shadihh9, 

Can you paste the screenshot of the above error with the content of the `/root/Desktop/recon/xxx/exmple` file?

**Comment by bauthard** [comment]
should be fixed with https://github.com/projectdiscovery/naabu/releases
