### ISSUE TITLE
[Bug] Could not create runner: Again

### ISSUE THREAD

**Issue by 1979139113** [projectdiscovery/naabu#281]
### Naabu version:

2.0.5

<img width="839" alt="图片" src="https://user-images.githubusercontent.com/24983597/158298774-2f6b4e04-5c20-4d72-b7ad-31cbc1c65617.png">

### Current Behavior:

<img width="884" alt="图片" src="https://user-images.githubusercontent.com/24983597/158298858-a9a7c884-16a9-41b1-9cd9-89359b4db59b.png">

### Expected Behavior:

get the right result.

### Steps To Reproduce:

mac with sudo will get this error

**Comment by Mzack9999** [comment]
@1979139113 Thanks for opening this issue. Unfortunately, I cannot reproduce it on the latest OSX, both with AMD64 and M1. Can you provide more information on the execution environment?

**Comment by 1979139113** [comment]
I dont know why, maybe its because my system has been updated, I tried again just now, and no problem has been found.
