### ISSUE TITLE
Feature: Changing the way output is returned in naabu

### ISSUE THREAD

**Issue by 0xrishabh** [projectdiscovery/naabu#29]
From:
{"host": "<host>", "ports": "80"}
{"host": "<host>", "ports": "443"}
{"host": "<host>", "ports": "8043"}

TO:
{"host": "<host>", "ports": "80,443,80443,...."}

I think this will be really helpful for hunters

**Comment by bauthard** [comment]
Hey, @0xrishabh, 

We do prints the results in this way, so it can be piped with other tools for further processing, can you share some example where the suggested format is useful?

**Comment by 0xrishabh** [comment]
I think it will be easy to pass it to Nmap only the "good" ports for further recon or save it in database
with the second format.

**Comment by bauthard** [comment]
I see what you mean and something already raised here https://github.com/projectdiscovery/naabu/issues/14, we will definitely see any workaround to pass the input to Nmap for service detection or any other checks, closing now as it's duplicate. 

we will see what we can do here, thanks again for pointing this out.
