### ISSUE TITLE
Displayed if the IP is part of a CDN in the output

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/naabu#308]
Hi Team,
I think it would be interesting in the JSON output to add a boolean to indicate if the IP is part of a CDN or not.
This would be useful for data parsing / data reuse purposes.

Like :
```
{"host":"domain.tld","ip":"104.16.99.52","port":443,"cdn":true,"timestamp":"2022-05-07T08:37:38.155294822Z"}
```

Regards

**Comment by ehsandeep** [comment]
@JoshuaMart this is something we expose with httpx, but can be done with naabu as well.

```
echo version-check.nuclei.sh | httpx -json -cdn | jq .
```

```
  "cdn": true,
  "cdn-name": "cloudflare",
  ```
