### ISSUE TITLE
SIGSEGV docker latest version

### ISSUE THREAD

**Issue by wellencamass** [projectdiscovery/naabu#320]
Hello, I'm running naabu like that:
``` sudo docker run --rm --cpu-shares 512 --privileged=true --ulimit nofile=1048576:1048576 -v configs:/configs/ -v dockerresults:/dockerresults --expose=22 -p 22:22 --net=host projectdiscovery/naabu -exclude-cdn -c 20 -rate 1000 -timeout 5000 -p 1-200 -list ips.txt -output " . $outputtxt ." -nmap-cli 'nmap -g 22 -Pn -v -sV --min-hostgroup 500 --script-timeout 8000m --host-timeout 40000m --max-scan-delay 20s --max-retries 3 --open -oX " . $nmapoutputdir . "{{ip}}.xml --stylesheet /configs/nmap/nmap.xsl -R  >> /dockerresults/out.txt 2>&1 ```

And this is what I usually get:
<img width="989" alt="изображение" src="https://user-images.githubusercontent.com/77920409/168277612-907c90fd-018d-412c-a05d-3085a6633a35.png">

**Comment by wellencamass** [comment]
there were ipv6 ips in the list and its possible that its the issue.

I think its better to handle those strings and ignore them instead of giving sigsegv :)

**Comment by ehsandeep** [comment]
@wellencamass it was due to ipv6 in the input and now fixed in the dev version as part of https://github.com/projectdiscovery/naabu/pull/325
