### ISSUE TITLE
 naabu doesn't work well in case of CWAP-WAF

### ISSUE THREAD

**Issue by 0cat-r** [projectdiscovery/naabu#341]
A common situation is that for example, I have 10 ips to scan all ports, but one of them has waf. For example, this time cwap-waf (qianxin security domain) naabu will scan each of his ports, and the speed is full, causing the entire project to be in a few days. can't be done in hours
![Snipaste_2022-06-01_10-54-46](https://user-images.githubusercontent.com/49912303/171318561-b41f3f46-cf05-42ca-9c5c-dfbdfb051744.png)

![Snipaste_2022-06-01_10-52-37](https://user-images.githubusercontent.com/49912303/171318311-454d75eb-c991-4e08-87ff-8a27949df512.png)

My suggestion is to identify waf and handle it like cdn

**Comment by 0cat-r** [comment]
I think a function can be added. If more than a certain number of ports are open, the IP address will be skipped.

**Comment by Mzack9999** [comment]
This will be worked on in https://github.com/projectdiscovery/cdncheck/issues/25
