### ISSUE TITLE
how use Nmap result with -nmap-cli 

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/naabu#377]
specified
-nmap-cli
And it is an optimized parameter. Can you use this result directly, and naabu will no longer do port scanning?

**Comment by ehsandeep** [comment]
Nmap results can't be used with `nmap-cli`, it can only be used to perform nmap scanning on found open ports by naabu

**Comment by hktalent** [comment]
@ehsandeep 
I hope to be able to reverse it, checkHaveNmap -> have -> doNmap -> use nmap result
no nmap -> naabu
Because nmap based on optimized parameters is always much faster than naabu

thanks

**Comment by safe6Sec** [comment]
> @ehsandeep I hope to be able to reverse it, checkHaveNmap -> have -> doNmap -> use nmap result no nmap -> naabu Because nmap based on optimized parameters is always much faster than naabu
> 
> thanks
> 
> The reason for using naabu is to achieve more functions based on golang integration

Hello, can you post the optimization parameters of nmap?

**Comment by hktalent** [comment]
@safe6Sec 
```
nmap -n --unique --resolve-all -Pn --min-hostgroup 64 --max-retries 0 --host-timeout 10m --script-timeout 3m -oX {filename} --version-intensity 9 --min-rate 10000 -T4
```
more you can see:
http://github.com/hktalent/scan4all

**Comment by safe6Sec** [comment]
> @safe6Sec
> 
> ```
> nmap -n --unique --resolve-all -Pn --min-hostgroup 64 --max-retries 0 --host-timeout 10m --script-timeout 3m -oX {filename} --version-intensity 9 --min-rate 10000 -T4
> ```
> 
> more you can see: [http://github.com/hktalent/scan4all](https://github.com/hktalent/scan4all)

nb

**Comment by hktalent** [comment]
> > @safe6Sec
> > ```
> > nmap -n --unique --resolve-all -Pn --min-hostgroup 64 --max-retries 0 --host-timeout 10m --script-timeout 3m -oX {filename} --version-intensity 9 --min-rate 10000 -T4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > more you can see: [http://github.com/hktalent/scan4all](https://github.com/hktalent/scan4all)
> 
> nb

<img width="861" alt="image" src="https://user-images.githubusercontent.com/18223385/177697890-537a7473-8fa7-4134-8f4c-744dee783960.png">

**Comment by safe6Sec** [comment]
> @safe6Sec
> 
> > > @safe6Sec
> > > ```
> > > nmap -n --unique --resolve-all -Pn --min-hostgroup 64 --max-retries 0 --host-timeout 10m --script-timeout 3m -oX {filename} --version-intensity 9 --min-rate 10000 -T4
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > more you can see: [http://github.com/hktalent/scan4all](https://github.com/hktalent/scan4all)
> > 
> > 
> > nb
> 
> <img alt="image" width="861" src="https://user-images.githubusercontent.com/18223385/177697890-537a7473-8fa7-4134-8f4c-744dee783960.png">

真的快，快麻了
