### ISSUE TITLE
Option to exclude full scan port scan that exceed a certain threshold

### ISSUE THREAD

**Issue by r00tSe7en** [projectdiscovery/naabu#379]
Is it possible to add a parameter that a host opens a certain threshold number of ports to filter out to scan the next target.
For example, if an ip has opened 100 ports, then it will not continue to scan this IP.

```console
   -port-threshold, -pts int              skip full port scan for defined port threshold
```

Example:

In the below example, `hackerone.com` host will be skipped when the open port counter is `> 5` when running active port scanning.

```
echo hackerone.com | naabu -pts 5
```

**Comment by ehsandeep** [comment]
Also mentioned here - https://github.com/projectdiscovery/naabu/discussions/367
