### ISSUE TITLE
Assets for Windows weren't released at v2.0.8

### ISSUE THREAD

**Issue by suzuki-shunsuke** [projectdiscovery/naabu#399]
Thank you for your great project.

I found there is no asset for Windows at the latest version v2.0.8.

https://github.com/projectdiscovery/naabu/releases/tag/v2.0.8

<img width="388" alt="image" src="https://user-images.githubusercontent.com/13323303/180591841-bac91412-15a3-4974-bdac-ed6bfe9865d1.png">

On the other hand, there are assets for Windows at v2.0.7.

https://github.com/projectdiscovery/naabu/releases/tag/v2.0.7

<img width="368" alt="image" src="https://user-images.githubusercontent.com/13323303/180591870-5a20c176-58fc-44c0-9147-065d4ca26c7b.png">

I checked the change log and Release Note, but I can't find the update to stop supporting Windows, so I think naabu still supports Windows.
https://github.com/projectdiscovery/naabu/releases/tag/v2.0.8
https://github.com/projectdiscovery/naabu/compare/v2.0.7...v2.0.8

Could you publish assets for Windows?

Thank you.

**Comment by ehsandeep** [comment]
@suzuki-shunsuke thanks for pointing this out, looks like some issue with window platform release automation - https://github.com/projectdiscovery/naabu/runs/7480416039?check_suite_focus=true

**Comment by ehsandeep** [comment]
@suzuki-shunsuke this is now fixed with latest release - https://github.com/projectdiscovery/naabu/releases/tag/v2.0.9

**Comment by suzuki-shunsuke** [comment]
Thank you for your fix!
