### ISSUE TITLE
[Feature Request] Would be great a stealth/passive/aggressive arg option

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/naabu#4]
Would be great a stealth/passive/aggressive arg option

_Originally posted by @bsysop in https://github.com/projectdiscovery/naabu/issues/2#issuecomment-577159206_

**Comment by Mzack9999** [comment]
@bsysop I've opened a new issue with your request for better tracking and plan the development. What you are requesting can be already accomplished with the `rate` parameter. I'm not sure if I fully understand the meaning of `passive`, did you mean `normal speed`?
Of course if it can be useful we can add some pre-configured template settings like `T1, T2, T3, T4, T5` of nmap, I suppose you are requesting this.

**Comment by bsysop** [comment]
Hi @Mzack9999, you right is the rate, passive is a normal scan (nmap T1/T2) and agressive is a T4 (T5 fails in many cases, could lead to anothers naabu bugs or lead to more controls)

I said just three templates for simplify, i think most of scans resume in that

**Comment by bauthard** [comment]
Hey @bsysop, we could do that, but that would bloat the CLI by adding additional complexity. What you are asking is easily possible using the `rate` parameter. Hence, I will close this issue. 

Thanks for the interest in this project.

**Comment by bsysop** [comment]
You right! Thanks @bauthard
