### ISSUE TITLE
Issue with nmap flag input

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/naabu#400]
### Naabu version:
master,dev

### Current Behavior:
`nmap` binary being accepted in the input.

Example:

```
echo hackerone.com | naabu -p 80 -nmap-cli "nmap -sV" -silent
```

### Expected Behavior:
`nmap` cmd should be accepted as input and substitute to `nmap`

Example:

```
echo hackerone.com | naabu -p 80 -nmap-cli "-sV" -silent
```

**Comment by Mzack9999** [comment]
@ehsandeep I think initially this was the idea. Still, later, it was opted to accept generic commands (nmap can be located anywhere or be available under aliases) and append the list of space-separated ips with `-p` and comma-separated ports for post-processing purposes. Do you think we should only execute the `nmap` binary?

**Comment by Mzack9999** [comment]
^ @ehsandeep could you confirm?

**Comment by ehsandeep** [comment]
> ^ @ehsandeep could you confirm?

Yes, as part of this feature, we should keep limited to nmap binary and execute only if nmap is configured / available to the users path, otherwise we can error it out.
