### ISSUE TITLE
[FTL] Could not create runner: socket: permission denied

### ISSUE THREAD

**Issue by arijitdirghanji** [projectdiscovery/naabu#401]
when i am try to running naabu showing this type of error  - > naabu -host hackerone.com

![image](https://user-images.githubusercontent.com/50274322/180631164-36165901-9f2e-4876-a09b-3a24d9b45d04.png)

![image](https://user-images.githubusercontent.com/50274322/180631156-20a3e657-95ca-40e8-95e5-cf17fd684484.png)

**Comment by ehsandeep** [comment]
@arijitdirghanji what's the output of `naabu -hc`?

**Comment by mobius07** [comment]
I have the same problem.

![1](https://user-images.githubusercontent.com/20757829/180643278-ae225c8b-a0b6-465c-a16f-7af411cfb58b.png)

**Comment by mmishalov** [comment]
Have the same issue

<img width="817" alt="image" src="https://user-images.githubusercontent.com/1223201/180645244-2fa0363d-232f-41b3-91c3-e6814cbc2357.png">

**Comment by xj90512** [comment]
maybe you can add this to you  /etc/sysctl.conf

echo "net.ipv4.ping_group_range = 0 2147483647" >> /etc/sysctl.conf

**Comment by ehsandeep** [comment]
thanks for reporting this @arijitdirghanji, @mmishalov @mobius07 this is now fixed with latest release - https://github.com/projectdiscovery/naabu/releases/tag/v2.0.9
