### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by c4ir0** [projectdiscovery/naabu#429]
I swear sth is wrong is hapenning with me why it's not working !!!!!!

![Capture](https://user-images.githubusercontent.com/108268587/190876883-306ad79c-ef82-44fa-aafc-84ed97ded128.JPG)

**Comment by presianbg** [comment]
@c4ir0 are you scanning via VPN interface (tun / wg ) ? If so, that might be the culprit of this issue.
I experience the same when my full tunnel Wireguard VPN is active.
