### ISSUE TITLE
Go does not download the latest repo version

### ISSUE THREAD

**Issue by BarikMana** [projectdiscovery/naabu#43]
Hello,

As of right now, Go does not download/install the latest repo version.

> go: downloading github.com/projectdiscovery/naabu v1.1.2

**Comment by bauthard** [comment]
Thank you @BarikMana, 

Go modules needs to be updated.

**Comment by Ice3man543** [comment]
Hey, this was an issue with our released tag which we forgot to follow semantic versioning required by go. It should be fixed now.

```
go: downloading github.com/projectdiscovery/naabu v1.1.3
go: found github.com/projectdiscovery/naabu/cmd/naabu in github.com/projectdiscovery/naabu v1.1.3
golang.org/x/net/icmp
```
