### ISSUE TITLE
Using as library documentation

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/naabu#432]
### Please describe your feature request:
A document including examples to use naabu into go projects + integration test

### Describe the use case of this feature:
As a developer, I wanted to integrate naabu into my go project to utilize all the features of naabu.

**Comment by nikkhilgoyal** [comment]
Want to use passive scan feature of naabu to get open ports.

**Comment by Mzack9999** [comment]
@nikkhilgoyal Just set `Passive` to `true` and provide a callback for `OnResult`:
```go
options := runner.Options{
	ResumeCfg: &runner.ResumeCfg{},
	Retries:   1,
	Host: "scanme.sh",
	Passive:   true,  // set to true
	OnResult:  func(hr *result.HostResult) {}, // provide a callback
}
```
