### ISSUE TITLE
[FTL] Could not run enumeration: Timeout

### ISSUE THREAD

**Issue by awei84** [projectdiscovery/naabu#449]
1.  When I call the python program to run naabu through celery, I get an error like this：
- ![image](https://user-images.githubusercontent.com/39472499/196884350-5b7b95dd-6a7c-4d75-a31f-8d5feb0ed425.png)
- ![image](https://user-images.githubusercontent.com/39472499/196884738-89c58dcc-4229-45e8-a9df-3157941ad9fb.png)

2.  When I run it directly in the python script it is ok, but the following problem occurs when I call this python program through the asynchronous task queue

3. My system is CentOS Linux release 7.9.2009 (Core)， It might be a problem with my own system, but I can't find the reason，Hope to get some help, thanks！

**Comment by ehsandeep** [comment]
@awei84 try using `-no-stdin` option

**Comment by awei84** [comment]
Thank you so much, everything is working!

**Comment by Sosiaka** [comment]
Thank u ❤️

**Comment by Sosiaka** [comment]
![Screenshot_2023-11-14-12-05-26_2560x1440](https://github.com/projectdiscovery/naabu/assets/113920954/5c110857-b53f-4bcb-b4aa-66602e7f076b)
![Screenshot_2023-11-14-15-22-39_2560x1440](https://github.com/projectdiscovery/naabu/assets/113920954/4e2b7b00-3546-4208-9815-8cf663624bdb)
I had same problem
