### ISSUE TITLE
-Pn

### ISSUE THREAD

**Issue by dsolstad** [projectdiscovery/naabu#45]
"-Pn | Perform ping probe to detect alive hosts"

Might be confusing when it means the opposite in nmap.

**Comment by Mzack9999** [comment]
@dsolstad - I understand your point, we do not perform probes by default unless requested. Do you think an extended more descriptive name would be more comprehensible (eg. `-ping-probe`)?

**Comment by Mzack9999** [comment]
It seems like that changing an existing option would introduce compatibility problems, considering that anyway it is clearly described and documented. Closing for now, thanks anyway for raising the question!
