### ISSUE TITLE
Upgrade dependency 

### ISSUE THREAD

**Issue by lucy9x** [projectdiscovery/naabu#450]
When using naabu, subfinder, httpx, nuclei as libraries for my personal project, I always have dependency conflict issue because the above projects use different versions of dependencies. 
For example: 
The current naabu uses `github.com/projectdiscovery/stringsutil v0.0.0-20220712170325-48c50c332cb4` while nuclei uses `github.com/projectdiscovery/stringsutil v0.0.1` which makes naabu and nuclei unusable as libraries on the same project due to conflict of stringsutil.Before medthod in https://github.com/projectdiscovery/naabu/blob/master/v2/pkg/scan/scan.go#L388

**Comment by Mzack9999** [comment]
@lucy9x Thanks for opening this issue, soon we will replace all utils library with one updated regularly at https://github.com/projectdiscovery/utils (not yet released)
