### ISSUE TITLE
Results across different -ports flag, -verify flag are inconsistent

### ISSUE THREAD

**Issue by CaptainFreak** [projectdiscovery/naabu#46]
<img width="607" alt="Screenshot 2020-07-02 at 9 03 59 AM" src="https://user-images.githubusercontent.com/20478531/86313547-04591880-bc43-11ea-8c70-8c5247d7d071.png">

Also if possible, can be good to add localhost scanning support too.

**Comment by Mzack9999** [comment]
@CaptainFreak - Thanks for opening the issue. I'm unable to reproduce it, anyway the PR #49 should make scans more reliable when run as normal user
