### ISSUE TITLE
UDP services standard probes

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/naabu#462]
### Please describe your feature request:
UDP services usually don't reply to empty probes. Therefore it's necessary to prepare a list of the most well-known services with a corresponding probe payload specific to the service and port combination that most likely will trigger a response.

Ref: https://nmap.org/book/scan-methods-udp-scan.html

**Comment by Mzack9999** [comment]
Depends on https://github.com/projectdiscovery/netdb/pull/27

**Comment by p0w1** [comment]
The console help should clearly state that the service discovery is only for UDP and not TCP at the moment

**Comment by Mzack9999** [comment]
Closing for the time being as nmap probes can't be used without breaking ToS
