### ISSUE TITLE
fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by arpitkarnak** [projectdiscovery/naabu#493]
### Steps To Reproduce:

While installation 

1. go build 

I got error 

# github.com/google/gopacket/pcap
/home/atom/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

-->

**Comment by ehsandeep** [comment]
@arpitkarnak see https://github.com/projectdiscovery/naabu/discussions/139 and readme.
