### ISSUE TITLE
Could not create runner: listen ip4:tcp : socket: protocol not supported

### ISSUE THREAD

**Issue by Ajm41** [projectdiscovery/naabu#495]

**Comment by ehsandeep** [comment]
@Ajm41 please include all the required info including output of `naabu -hc`

**Comment by Ajm41** [comment]
└─# naabu -hc
Version: 2.1.1
Operative System: linux
Architecture: amd64
Go Version: go1.19.3
Compiler: gc
Privileged/NET_RAW: Ok
Config file "/root/.config/naabu/config.yaml" Read => Ok
Config file "/root/.config/naabu/config.yaml" Write => Ok
IPv4 connectivity to scanme.sh:80 => Ok
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: connection refused)

**Comment by ehsandeep** [comment]
tracking at https://github.com/projectdiscovery/naabu/issues/498
