### ISSUE TITLE
not able to download

### ISSUE THREAD

**Issue by sushantdhopat** [projectdiscovery/naabu#502]
when I was trying to download throw `go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
`

facing error like this on my VPS

`# github.com/google/gopacket/pcap
go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
`

**Comment by 9MaDdy16** [comment]
Try installing pcap library.
Use sudo apt-get install libpcap-dev.

**Comment by ehsandeep** [comment]
@sushantdhopat see https://github.com/projectdiscovery/naabu/discussions/139

**Comment by sushantdhopat** [comment]
Thank you so much it resolved i installed it successfully
