### ISSUE TITLE
Naabu not displaying any result

### ISSUE THREAD

**Issue by abhinavsecond** [projectdiscovery/naabu#513]
### Naabu version:
2.0.5

### Current Behavior:
naabu not showing any result

### Steps To Reproduce:

1. Run 'naabu -host hackerone.com '
2. No result displayed
-->
![image](https://user-images.githubusercontent.com/103136282/208439422-52915203-9c2d-4124-8c3d-f99e3662af18.png)

**Comment by mudsybugg** [comment]
facing the same issue

**Comment by Mzack9999** [comment]
It looks like a networking error while attempting to resolve hackerone.com to its ips. Are you able to execute the following commands:

```console
curl hackerone.com
nmap -p 80 hackerone.com
```
Also, can you provide more info on the execution environment? For example, are you using a VPN?

**Comment by abhinavsecond** [comment]
No, I am not using any proxy, vpn etc.
I have tried the command you have mentioned above. Nmap is working fine but
curl hackerone.com didn't give any results. However, curl https://hackerone
worked fine
[image: image.png]

**Comment by Mzack9999** [comment]
If also curl is not working, it might be something related to your network. Could you provide more info related to the following:

- Network configuration
- Output of `naabu -hc`
- Operative system and architecture
- Any particular configuration (e.g. VPN)

The only thing I can think of is that packets are not routed correctly to the destination, but it's hard to identify the possible reasons without more info.

**Comment by abhinavsecond** [comment]
Update: The issue is resolved. Try to switch b/w NAT and Bridge network
