### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gok26** [projectdiscovery/naabu#543]
### Discussed in https://github.com/projectdiscovery/naabu/discussions/542

<div type='discussions-op-text'>

<sup>Originally posted by **Gok26** January 31, 2023</sup>
github.com/projectdiscovery/naabu/v2/cmd/naabu
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpcap: No such file or directory
collect2: error: ld returned 1 exit status

how to fix this error?</div>

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/naabu/discussions/542#discussioncomment-4832005
