### ISSUE TITLE
Scanning open ports 

### ISSUE THREAD

**Issue by ribersec** [projectdiscovery/naabu#55]
Scanning for open ports is not reliable.
I have tried different rates from 50-1000 but still i am getting different responses. like below.
echo 'hackerone.com' | naabu -ports top-100 -rate 100
![image](https://user-images.githubusercontent.com/43514938/87763599-54c0a080-c815-11ea-8b8f-46545245fe88.png)

![image](https://user-images.githubusercontent.com/43514938/87763655-6e61e800-c815-11ea-8354-fe92dfc33d31.png)

and for sure that port 8443 is not open on hackerone.com (as far as i know)

**Comment by ribersec** [comment]
additional info, even with the command naabu -host hackerone i am getting different output
![image](https://user-images.githubusercontent.com/43514938/87764386-943bbc80-c816-11ea-9e20-0437db820e0c.png)

**Comment by bauthard** [comment]
Hey, this shouldn't be the expected behaviour, I will confirm and update you if something got changed in last update.

thank you for creating this issue.

**Comment by ribersec** [comment]
Okay, if i can provide anything else let me know!

**Comment by eschultze** [comment]
I just saw that `-ports -top1000` gives fewer results than `ports -top100`. Is this the expected behavior?

Example:
```
me@host:~/path$ subfinder -silent -d $DOMAIN | naabu -silent -ports top-100 | wc -l
82
me@host:~/path$ subfinder -silent -d $DOMAIN | naabu -silent -ports top-1000 | wc -l
3
```
