### ISSUE TITLE
How to use `-sn` parameter under windows

### ISSUE THREAD

**Issue by komomon** [projectdiscovery/naabu#562]
![image](https://user-images.githubusercontent.com/52700174/219595430-a5fc1e39-34b8-43ee-b359-7c267d2f657e.png)

**Comment by Mzack9999** [comment]
@komomon Unfortunately, windows raw packet manipulation is not yet supported. The integration will be done in a future release as we need to test gopacket with winpcap. Anyway, I've implemented a PR that makes the error more explicit.
