### ISSUE TITLE
privileges.isPrivileged throws stacktrace

### ISSUE THREAD

**Issue by DeC1pher** [projectdiscovery/naabu#568]
Hi Team,

when running naabu on `armv7l` and go version `go1.20.1` I get following error:

```
runtime: g 1: unexpected return pc for runtime.doInit called from 0x0
stack: frame={sp:0x244cc80, fp:0x244cda8} stack=[0x244c000,0x244d000)
0x0244cc00:  0x00000000  0x00b25858  0x017d1bf0  0x00000000
0x0244cc10:  0x00000000  0x00000000  0x00000000  0x0006ff60 <runtime.sigpanic+0x0000026c>
0x0244cc20:  0x00b25858  0x017d1bf0  0x002480b0 <github.com/projectdiscovery/naabu/v2/pkg/privileges.isPrivileged+0x00000
100>  0x00003c01
0x0244cc30:  0x00000000  0x00000000  0x00002000  0x00000000
0x0244cc40:  0x024020f0  0x002480b0 <github.com/projectdiscovery/naabu/v2/pkg/privileges.isPrivileged+0x00000100>  0x0006
9198 <runtime.doInit+0x00000054>  0x017e5370
0x0244cc50:  0x00000000  0x00000000  0x00000000  0x00000000
0x0244cc60:  0x00000000  0x00000000  0x00000000  0x00000000
0x0244cc70:  0x00000000  0x00000000  0x00000000  0x00000000
....
```

looks like this is related to [this](https://github.com/projectdiscovery/utils/pull/73)?

Thanks!

**Comment by Mzack9999** [comment]
@DeC1pher, I don't think it's related to https://github.com/projectdiscovery/utils/pull/73, as that issue was preventing naabu from compiling. Instead, here is a runtime error. It could be related to rare bugs/instabilities with new go versions. Are you able to reproduce the same with go1.19 and go1.20?

**Comment by DeC1pher** [comment]
Hi @Mzack9999 ,

thanks for ur reply!
Already tried downgrading to go1.19 and got the exact same issue.
Looks like it only works with <go1.19.

Full command is only `naabu` without any parameter. 
Also the `katana` project has the exact same issue.

**Comment by Mzack9999** [comment]
I've been running the tools on a raspberry, apparently without issues. Do you have any suggestions on how to replicate the same execution environment which is causing the crash on your side? For example, with VirtualBox or Qemu?

**Comment by DeC1pher** [comment]
Hi @Mzack9999,

sorry I have no other idea how u could replicate the issue.
For the same issue on `katana` I figured out that when I replace following:

```
/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.4-0.20221222195055-f7d250fc55af/permission/permission_linux.go
```

with the contents from

```
https://github.com/projectdiscovery/utils/blob/main/permission/permission_other.go
```

It works again.
I think this is the exact same issue what we have here too.

```
github.com/projectdiscovery/naabu/v2/pkg/privileges.isPrivileged()
        /home/pi/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.1.2/pkg/privileges/privileges_lin
ux.go:33 +0x100 fp=0x2d2fc80 sp=0x2d2fc48 pc=0x283b94
```

Hope this helps!
