### ISSUE TITLE
exclude `IP` / `Port` / `Host` option is not working after last update

### ISSUE THREAD

**Issue by as3ddd** [projectdiscovery/naabu#586]
Hello,

when i try to exclude ports using -ep or  -exclude-ports  
the outpust still have excluded ports on it.

```console
naabu -host hackerone.com -ep 80

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

		projectdiscovery.io

[INF] Current naabu version 2.1.4 (latest)
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host hackerone.com (104.16.100.52)
hackerone.com:80
```

tried more than once.

Thanks

**Comment by NezHacker** [comment]
Yes, I also encountered this problem. When I use - exclude ports 80,22,25443, it even outputs ports like 80，443

**Comment by as3ddd** [comment]
@NezHacker  I guess we are using the same command haha 🤣

**Comment by NezHacker** [comment]
> @NezHacker I guess we are using the same command haha 🤣

mabe haha

**Comment by hishammir** [comment]
@as3ddd @NezHacker Hi guys, Any Solution so far?

**Comment by NezHacker** [comment]
> @as3ddd @NezHacker大家好，到目前为止有什么解决方案吗？
no

**Comment by ehsandeep** [comment]
This is fixed in latest release.
