### ISSUE TITLE
pps rate is more and more smaller

### ISSUE THREAD

**Issue by leveryd** [projectdiscovery/naabu#589]
### Naabu version:

v2.1.1

### Current Behavior:

during scan, the pps rate is more and more low, from 500(pps) to 8(pps)

### Expected Behavior:

keep the same pps rate during the whole scan

### Steps To Reproduce:

```
docker run projectdiscovery/naabu:v2.1.1 -l /tmp/hosts -r 114.114.114.114,8.8.8.8 -ec -stats -p 80,443 -json -o /tmp/result
```

u can get `/tmp/hosts` on the attachment

<img width="605" alt="image" src="https://user-images.githubusercontent.com/1846319/224245756-c5347ab6-ba93-487e-ada5-ab5be78321aa.png">

### Anything else:

[hosts.tgz](https://github.com/projectdiscovery/naabu/files/10939423/ip-result.tgz)

**Comment by Mzack9999** [comment]
@leveryd Thanks for opening this issue. I'm trying with the set of hosts, but I only hit the rate limit. Are you facing this issue at every scan with large lists?

**Comment by leveryd** [comment]
i am not sure it will happen every time or not, but i am sure it happens in nuclei too.

i will find time to retest it, to see if it happen every scan.

**Comment by Mzack9999** [comment]
Closing - Let us know if this needs more investigation
