### ISSUE TITLE
Host discovery support in windows

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/naabu#592]
### Please describe your feature request:

Follow up ticket - https://github.com/projectdiscovery/naabu/issues/562#issuecomment-1462993239

**Comment by Mzack9999** [comment]
On Hold - Two pre-requisites are necessary:
- [npcap](https://npcap.com/) installed on the system. Probably this can't be automated as it breaks nmap TOS
- Enable support for pcap on windows (trivial via conditional build + few runtime checks for windows OS)

**Comment by Mzack9999** [comment]
Closing as not planned - It would break nmap ToS
