### ISSUE TITLE
Issue with UDP port scanning

### ISSUE THREAD

**Issue by identityxidentityx** [projectdiscovery/naabu#603]
`naabu -host scanme.nmap.org -p 0-65535,u:0-65535`

_scanme.nmap.org:22
scanme.nmap.org:80
scanme.nmap.org:9929
scanme.nmap.org:31337
scanme.nmap.org:36197_  (the same scan in the same host will report random closed ports as opened)

Port 36197 is closed. Naabu reports it as opened.
Port 123 (UDP) is opened. Nabu doesn't report it.

**Comment by identityxidentityx** [comment]
Nmap scan:

PORT      STATE    SERVICE
22/tcp    open     ssh
80/tcp    open     http
9929/tcp  open     nping-echo
11211/tcp filtered memcache
31337/tcp open     Elite
123/udp   open     ntp

**Comment by Mzack9999** [comment]
Depends on https://github.com/projectdiscovery/naabu/issues/539

**Comment by Mzack9999** [comment]
Closing for the time being as nmap probes can't be used without breaking ToS
