### ISSUE TITLE
"retries" option questions

### ISSUE THREAD

**Issue by gy741** [projectdiscovery/naabu#61]
Hello,

I'm looking for optimization options.

Is the "retries" option required?

If data is set to zero, it cannot be detected properly.

For example:

```
$ naabu  -retries 0 -host google.com
[INF] Starting scan on host google.com (172.217.5.110)
[INF] No ports found on google.com (172.217.5.110). Host seems down
```

```
$ naabu -retries 1 -host google.com
[INF] Starting scan on host google.com (172.217.5.110)
[INF] Found 2 ports on host google.com (172.217.5.110)
google.com:443
google.com:80
```

Thanks

**Comment by bauthard** [comment]
Hey @gy741, 

As default it is set to 1, so you don't need set as 0, you can use it when you know that target which requires some additional retries, it's more control to the user, but keeping is 0 is something we do not suggest. 

Heads up:- we are reworking on `naabu` as a whole, so expect some major changes in the future. 

Regards.
