### ISSUE TITLE
bash: /usr/bin/naabu: No such file or directory

### ISSUE THREAD

**Issue by sudo-curioso** [projectdiscovery/naabu#62]
Hey Team! Hope You all are Doing Well.
I hv moved it to /usr/bin/naabu, but still the error is  :
bash: /usr/bin/naabu: No such file or directory

Hope you will Help me Out cause i m Stuck here and am Very Desperate to Use naabu

**Comment by srinivasch09** [comment]
Yes Getting Same error, can you please add how to install though GitHub links.

**Comment by bauthard** [comment]
@sudo-curioso @srinivasch09 this project is under rework, about installing the tool, you can simply pick the binary from here https://github.com/projectdiscovery/naabu/releases for you system that is ready to use.

**Comment by bauthard** [comment]
we will update install steps using multiple ways in the next update.

**Comment by bauthard** [comment]
This will be fixed automatically on the next release as we updated the go releaser for this issue.

**Comment by bauthard** [comment]
Closing as this is fixed.
