### ISSUE TITLE
Why was the -si option removed?

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/naabu#625]
I noticed in https://github.com/projectdiscovery/naabu/commit/860f9ab772c10c642f722898bff6e80305471b33
The -si option was removed in , is this intentional?
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/18167071/228420415-a401a0c4-1402-4bb0-98c6-ba94b1464257.png">
Is it possible to modify the option description of the readme and explain it in the release

**Comment by CzarnyKot1024** [comment]
Same issue. I am unable to use v2.1.3-2.1.5, because of -SI flag removal.

**Comment by Mzack9999** [comment]
The option is restored in https://github.com/projectdiscovery/naabu/pull/639 but marked as deprecated. Now the stats of a scan are always available at `http://localhost:63636:`
```console
# To check a running naabu instance
curl http://localhost:63636 | jq
```
