### ISSUE TITLE
-exclude-hosts not work when Perform Only Host Discovery

### ISSUE THREAD

**Issue by cyal1** [projectdiscovery/naabu#627]
Version: 2.1.5
`sudo naabu -sn -host 10.241.20.0/24 -exclude-hosts 10.241.20.70 -silent`
<img width="668" alt="image" src="https://user-images.githubusercontent.com/33282478/228514469-fb58574d-edac-4d4e-802c-074a404e2bf6.png">

**Comment by ehsandeep** [comment]
@cyal1 this is now fixed in the latest release.
