### ISSUE TITLE
Installation problem: 2.1.5

### ISSUE THREAD

**Issue by x0341** [projectdiscovery/naabu#653]
### Current Behavior:
Installation dependencies - missing files
go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest

### Expected Behavior:
Installation done with success

### Steps To Reproduce:
go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest

github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by ehsandeep** [comment]
@x0341 see [prerequisite](https://github.com/projectdiscovery/naabu#prerequisite) section. 

- https://github.com/projectdiscovery/naabu#prerequisite
- https://github.com/projectdiscovery/naabu/discussions/139
