### ISSUE TITLE
[research] strategies for distributing scans in multiple cases

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/naabu#66]
Possible scenario to consider for port scan distribution and keeping reliability at priority. 

- [ ] Single host single (limited) ports.
- [ ] Single host (limited) multiple ports.
- [ ] Multiple hosts single port.  
- [ ] Multiple hosts multiple ports

related to this, a few more things to consider. 

- [ ] Port randomisation 
- [ ] Sequential scan

**Comment by Mzack9999** [comment]
Iterating ports over all targets seems to fit all scenarios
