### ISSUE TITLE
results are not displayed at real time

### ISSUE THREAD

**Issue by gsh3ll** [projectdiscovery/naabu#666]
### Naabu version:

Current Version: 2.1.6

### Current Behavior:
run naabu with `-v` or `-veerboes`,the results during the scanning process will not appear on the terminal.Results appear only after the program has finished running.

### Expected Behavior:
like nmap,Real-time display of scanning results.

### Steps To Reproduce:
1. Run `./naabu -verbose -p - -host ip_target`
2. see photo:
![image](https://user-images.githubusercontent.com/64195264/237031494-84d2648c-ca31-4a0c-a0b0-60cb04c11a42.png)

### Anything else:
nothin

**Comment by pdelteil** [comment]
I'm having the same issue.... 

No fixes?

**Comment by QU35T-code** [comment]
Same issue here

**Comment by Mzack9999** [comment]
The results are shown in the end by design to provide the ports deduplicated within a json slice. You can try with the `-stream` option. Keep an eye on https://github.com/projectdiscovery/naabu/pull/946 that along better resource handling, should provide the capability of native stream in/out.

**Comment by pdelteil** [comment]
> The results are shown in the end by design to provide the ports deduplicated within a json slice. You can try with the `-stream` option. Keep an eye on #946 that along better resource handling, should provide the capability of native stream in/out.

I didn't understand the reason. 

I think the output should follow the output of other project discovery tools. They are pretty intuitive and easy to handle.

**Comment by ehsandeep** [comment]
@pdelteil @QU35T-code @gsh3ll this is now supported in latest release.
