### ISSUE TITLE
fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by valaDevs** [projectdiscovery/naabu#680]
### Naabu version:
latest

### Current Behavior:

fatal error while installing on my PC
### Steps To Reproduce:

go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest

it will throw this error:
fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~

**Comment by valaDevs** [comment]
installed an dependency and fixed the issue

**Comment by x0341** [comment]
@valaDevs which dependencies ?
