### ISSUE TITLE
[bug] Scans on windows don't work

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/naabu#7]
Windows scans get stuck without finishing. Tried on Windows 10 x64 with npcap latest version.

**Comment by atikrahman1** [comment]
Trying to use naabu on windows  10 go version go1.14.2 windows/amd64. The scan does finish at all. 

![image](https://user-images.githubusercontent.com/25384315/79045202-ae6c6a00-7c2b-11ea-9846-48f79990e571.png)

**Comment by Droidzzzio** [comment]
Problem in scanning with windows. Added a Screenshot 
![naabu-result](https://user-images.githubusercontent.com/34626959/80710424-57f89a00-8b0c-11ea-825d-4acc8a23c4b6.PNG)

and why these WRN , DBG, INF are not parsing on my terminal .
