### ISSUE TITLE
Optional flag support to exclude CDN hosts for full port scan

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/naabu#70]
We can integrate [cdncheck](https://github.com/projectdiscovery/cdncheck) into naabu for this which checks and returns `true` or `false` for a given host. 

If this flag is used and it returns `true` we can simply avoid the host for full port scan and perform only 80 and 443 checks. 

Suggested flag:- `exclude-cdn`

**Comment by Mzack9999** [comment]
- [ ] Fix https://github.com/projectdiscovery/cdncheck build dependency

**Comment by bauthard** [comment]
@Mzack9999 https://github.com/projectdiscovery/cdncheck this is now FOSS.
