### ISSUE TITLE
[feature] Documentation update - README to include steps for MacOS when using helper scripts

### ISSUE THREAD

**Issue by CasperGN** [projectdiscovery/naabu#75]
**Is your feature request related to a problem? Please describe.**
There is required steps that, although fairly trivial, would be beneficial to document in the README file.

**Describe the solution you'd like**
I propose to append the following to the section regarding Helper scripts:

---

## Helper scripts on MacOS

The helper scripts require `gsed` to run. `gsed` is available through brew as  

```bash
brew install gsed
```

With Catalina and onward Bash has been replaced by Zsh as default shell. Although Bash is still present, it may not continue to be and as such, your commands would look as 

```bash
> echo hackerone.com | naabu -silent | zsh naabu2nmap.sh
> echo hackerone.com | naabu -silent | zsh prepare4nmap.sh
```
  
---

/ Casper

**Comment by bauthard** [comment]
Helper scripts will be deprecated with this https://github.com/projectdiscovery/naabu/issues/78, so no action needed on this.

**Comment by CasperGN** [comment]
Thanks @bauthard, that's a neat feature imo. I'll close on that note.
