### ISSUE TITLE
Get rid of libpcap dependency

### ISSUE THREAD

**Issue by YugoCode** [projectdiscovery/naabu#781]
Why is the dependency on _libpcap_ needed? Do you have plans to remove it in the future?

When using naabu as a library, you don't have the "run anywhere" advantages of Golang binaries anymore, as you have the _libpcap_ dependency.

Thanks for your input on this in advance!

**Comment by Nemesis0U** [comment]
Libpcap causes problems on some distros

**Comment by All3yp** [comment]
@YugoCode 
To solve this error when tryed install, you can be able to run:

`sudo apt-get install libpcap-dev`

**Comment by Mzack9999** [comment]
Unfortunately this is very hard to implement as it's hard-coded within `gopacket` (ref. https://github.com/google/gopacket/blob/32ee38206866f44a74a6033ec26aeeb474506804/pcap/pcap_unix.go#L26). For the time being, sadly, it's a necessary prerequisite.
