### ISSUE TITLE
 package crypto/ecdh is not in GOROOT

### ISSUE THREAD

**Issue by N0o01** [projectdiscovery/naabu#807]
abc:~# go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest

go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.18/src/crypto/ecdh)
root@ser230545925848:~#

**Comment by MetzinAround** [comment]
Hi @N0o01 , 

When posting, please choose either an issue or a discussion for your question, but not both. 
Closing this issue in favor of the discussion where I answered your questions. Let us know if upgrading Go to 1.20 doesn't help. 

discussion - https://github.com/projectdiscovery/naabu/discussions/806
