### ISSUE TITLE
Service Discovery & Service Version flags doesn't seem to work

### ISSUE THREAD

**Issue by Jayian1890** [projectdiscovery/naabu#813]
### Current Behavior:
Output open ports without service version and or service discovery information

### Expected Behavior:
Output open ports with service version and or service discovery information

### Steps To Reproduce:
sudo naabu -sD -sV -sn -host 192.168.1.0/24

**Comment by Mzack9999** [comment]
It's under development at https://github.com/projectdiscovery/naabu/pull/670

**Comment by ehsandeep** [comment]
@Jayian1890 Service discovery is not yet implemented/supported in Naabu, you can follow the linked PR and issue for the update.
