### ISSUE TITLE
exclude-hosts flag only works with IP and CIDR

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/naabu#821]
### Naabu version:
`main|dev`

### Current Behavior:
The `-exclude-hosts` flag only works with IP and CIDRs

### Expected Behavior:
The flag should also work with FQDN

### Steps To Reproduce:
```console
$ cat exclude.txt
scanme.sh
$ naabu -host scanme.sh -exclude-hosts exclude.txt -p 80

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.1.8 (latest)
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host scanme.sh (128.199.158.128)
scanme.sh:80
```

**Comment by kljunowsky** [comment]
When can we expect this issue to be resolved? Thanks in advance! @Mzack9999

**Comment by Mzack9999** [comment]
@kljunowsky It's implemented as draft in https://github.com/projectdiscovery/naabu/pull/823 - In order to exclude targets from file, you need to use `exclude-file` (in the future both options should be probably merged into just `exclude-hosts`)

**Comment by ehsandeep** [comment]
fixed in https://github.com/projectdiscovery/naabu/releases/tag/v2.1.9

**Comment by kljunowsky** [comment]
Thanks for the prompt action!
