### ISSUE TITLE
Question regarding packaging v2.0.0 and licensing

### ISSUE THREAD

**Issue by alebcay** [projectdiscovery/naabu#84]
Hello, I'm a maintainer with the [Homebrew](https://brew.sh) package manager. Just wanted to verify that the release v2.0.0 was re-tagged recently and that this was intentional (https://github.com/projectdiscovery/naabu/commit/6475f7bc1795555c9a1833d5529855ab8a14fdf3).

Also, regarding the licensing for this project is it licensed under SPDX identifier `GPL-3.0-only` or `GPL-3.0-or-later`? Thanks!

**Comment by bauthard** [comment]
Hi @alebcay, 

Yes, I can confirm it was intentional due to an issue we had with release workflow, also we have updated the license to MIT.

**Comment by alebcay** [comment]
Thanks for the information! 👍
