### ISSUE TITLE
No valid ipv4 or ipv6 targets were found

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/naabu#857]
**Naabu version :** 2.1.9

Hello,
In some cases, the following error may be displayed even though the IP is valid 

For example, the following case has a service listening on port 443
```
root@2da0d43ddd77:~# naabu -host 18.136.44.35 -port 443
[FTL] Could not run enumeration: no valid ipv4 or ipv6 targets were found
```

Regards

**Comment by dogancanbakir** [comment]
@JoshuaMart, I was unable to reproduce the issue.
```console
$ go run . -host 18.136.44.35 -port 443

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.1.9 (latest)
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host 18.136.44.35 (18.136.44.35)
18.136.44.35:443
```

@Mzack9999, Looked at the code but couldn't find anything useful. Am I missing something?

**Comment by JoshuaMart** [comment]
Yes, I just tested from a fresh EC2 instance and I have the same problem.
However, it works on my local PC.

Simple TCPDump when I run the Naabu command : 
```
root@ip-172-31-30-230:~# tcpdump host 18.136.44.35 -v
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
15:45:23.605181 IP (tos 0x0, ttl 64, id 42898, offset 0, flags [DF], proto TCP (6), length 44)
    ip-172-31-30-230.eu-west-1.compute.internal.45437 > ec2-18-136-44-35.ap-southeast-1.compute.amazonaws.com.http: Flags [S], cksum 0xd8a8 (correct), seq 0, win 1024, options [mss 1460], length 0
15:45:23.605217 IP (tos 0x0, ttl 64, id 42899, offset 0, flags [DF], proto TCP (6), length 44)
    ip-172-31-30-230.eu-west-1.compute.internal.45437 > ec2-18-136-44-35.ap-southeast-1.compute.amazonaws.com.https: Flags [.], cksum 0xd72e (correct), ack 0, win 1024, options [mss 1460], length 0
15:45:23.605253 IP (tos 0x0, ttl 64, id 31948, offset 0, flags [DF], proto ICMP (1), length 28)
    ip-172-31-30-230.eu-west-1.compute.internal > ec2-18-136-44-35.ap-southeast-1.compute.amazonaws.com: ICMP echo request, id 3730, seq 1, length 8
15:45:23.605266 IP (tos 0x0, ttl 64, id 31949, offset 0, flags [DF], proto ICMP (1), length 40)
    ip-172-31-30-230.eu-west-1.compute.internal > ec2-18-136-44-35.ap-southeast-1.compute.amazonaws.com: ICMP time stamp query id 3730 seq 0, length 20
```

A more complete pcap : https://transfer.sh/51qCyW8OSw/naabu.pcap

Just in case, I used an EC2 T2.micro Ubuntu 22.04 Linux/amd64 instance with security rules authorizing all incoming and outgoing traffic.

**Comment by Mzack9999** [comment]
@JoshuaMart do you get any error message by using the `verbose` or `debug` flag? Also could you try to execute `naabu -hc` (it can help identifying potential network issues).
From the provided pcap it seems like the host is not responding to any discovery probe from naabu:
<img width="1223" alt="Screenshot 2023-11-14 at 10 46 37" src="https://github.com/projectdiscovery/naabu/assets/13421144/545251aa-e518-4c9b-9482-c1dde2f510e7">

If you want to skip the discovery phase you need to use the `-Pn` flag. We also plan to implement additional discovery probes tracked at https://github.com/projectdiscovery/naabu/issues/726 that should cover this specific case

**Comment by JoshuaMart** [comment]
Hi,
Nothing special with `verbose` or `debug` flag, Here is the output with `-hc` : 

```
root@ip-172-31-16-32:~# naabu -host 18.136.44.35 -port 443 -hc
Version: 2.1.9
Operative System: linux
Architecture: amd64
Go Version: go1.20.8
Compiler: gc
Privileged/NET_RAW: Ok
Config file "/root/.config/naabu/config.yaml" Read => Ok
Config file "/root/.config/naabu/config.yaml" Write => Ok
TCP IPv4 connectivity to scanme.sh:80 => Ok
TCP IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: network is unreachable)
UDP IPv4 connectivity to scanme.sh:80 => Ok
UDP IPv6 connectivity to scanme.sh:80 => Ko (dial udp6 [2400:6180:0:d0::91:1001]:80: connect: network is unreachable)
```

The `-Pn` flag work, but I don't think it's a viable solution when a lot of hosts are scanned.

Furthermore, as I said, this case works well locally on my PC, but not on a VPS. I've tested different EC2 instances and even different providers, and the problem is recurrent between all instances.

Note : For this new test, I started a new EC2 instance
![image](https://github.com/projectdiscovery/naabu/assets/17493961/73ed9b73-cd79-4210-8cfc-b03c7ef11466)

Is it possible for you to test on your own on an EC2 instance ? Just to confirm.
On my side, I asked a friend, he's got the problem too with this IP.

Regards

**Comment by dogancanbakir** [comment]
@JoshuaMart,
I got the same result while testing on the AWS/EC2 instance.
```console
$ naabu -host 18.136.44.35 -port 443

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

		projectdiscovery.io

[INF] Current naabu version 2.1.9 (latest)
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host 18.136.44.35 (18.136.44.35)
18.136.44.35:443

$ naabu -host 18.136.44.35 -port 443 -hc
Version: 2.1.9
Operative System: linux
Architecture: amd64
Go Version: go1.20.11
Compiler: gc
Privileged/NET_RAW: Ko
Config file "/home/ubuntu/.config/naabu/config.yaml" Read => Ok
Config file "/home/ubuntu/.config/naabu/config.yaml" Write => Ok
TCP IPv4 connectivity to scanme.sh:80 => Ok
TCP IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: network is unreachable)
UDP IPv4 connectivity to scanme.sh:80 => Ok
UDP IPv6 connectivity to scanme.sh:80 => Ko (dial udp6 [2400:6180:0:d0::91:1001]:80: connect: network is unreachable)
```
<img width="1206" alt="image" src="https://github.com/projectdiscovery/naabu/assets/65292895/cc8e03ec-692c-44b5-94b1-270fce15ee6a">


Let me know if you have any questions.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.

**Comment by JoshuaMart** [comment]
Sorry for the late response, I'm investigating the problem to try to understand the cause since I can reproduce with several providers.

Can I know in which AWS region you launched your EC2 instance ?

Regards

**Comment by dogancanbakir** [comment]
@JoshuaMart, Of course, it is `eu-central-1`.

**Comment by JoshuaMart** [comment]
Well for my part it doesn't work either from eu-central-1
A friend tried it, it didn't work for him either, so I don't know why it works for you.

So for now we can keep this closed...maybe someone else will have a similar problem one day

**Comment by lucasgates** [comment]
I am seeing the same issue, but it only occurs when running as root on Ubuntu 23.10 on a VPS. On my desktop it works both with a regular user and running as root

Running as root:
`
root@vps:/home/lucas/work# naabu -list asn.txt 

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

		projectdiscovery.io

[INF] Current naabu version 2.3.0 (latest)
[INF] Running host discovery scan
[INF] Running SYN scan with CAP_NET_RAW privileges
[FTL] Could not run enumeration: no valid ipv4 or ipv6 targets were found
`

I am running version 2.3.0.
