### ISSUE TITLE
naabu: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sey8** [projectdiscovery/naabu#875]
naabu: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

**Comment by dogancanbakir** [comment]
@sey8, see
https://github.com/projectdiscovery/naabu#prerequisite
https://github.com/projectdiscovery/naabu/discussions/139
https://github.com/projectdiscovery/naabu/issues/660

**Comment by dogancanbakir** [comment]
Closing this. Let us know if you have any questions.
