### ISSUE TITLE
Naabu fails to build on Amazon Linux (arm architecture tested)

### ISSUE THREAD

**Issue by mailler0xa** [projectdiscovery/naabu#890]
### Naabu version:
Current main branch release and the provided archived sources.
(https://github.com/projectdiscovery/naabu.git and the archives in https://github.com/projectdiscovery/naabu/releases/)

### Current Behavior:
Trying to install naabu on Amazon Linux results in a failure with the following output when runnign go install: `go: downloading aead.dev/minisign v0.2.0
go/pkg/mod/github.com/minio/selfupdate@v0.6.1-0.20230907112617-f11e74f84ca7/minisign.go:8:2: unrecognized import path "aead.dev/minisign": reading https://aead.dev/minisign?go-get=1: 404 Not Found`

When running make on the provided sources, this is the error: `go build -v  -ldflags '-extldflags "-static"' -o "naabu" cmd/naabu/main.go
go: downloading aead.dev/minisign v0.2.0
../../../../go/pkg/mod/github.com/minio/selfupdate@v0.6.1-0.20230907112617-f11e74f84ca7/minisign.go:8:2: unrecognized import path "aead.dev/minisign": reading https://aead.dev/minisign?go-get=1: 404 Not Found
make: *** [Makefile:15: build] Error 1`

### Expected Behavior:
Naabu should build successfully.

### Steps To Reproduce:
1. Run  `go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest` on Amazon Linux (arm architecture) as is when installing naabu directly via go.
2. For the archives, after extracting the archives, run `make` while on v2 directory inside naabu.
3. Both cases will result in failures as described in the current behavior.
```[tasklist]
### Tasks
```

**Comment by dogancanbakir** [comment]
@mailler0xa , See https://github.com/projectdiscovery/subfinder/issues/1055. Closing this.

**Comment by mailler0xa** [comment]
@dogancanbakir Thanks. I got it to work.
