### ISSUE TITLE
Naabu does not work if ipv6 is disabled on kernel level

### ISSUE THREAD

**Issue by psyray** [projectdiscovery/naabu#914]
### Naabu version:
**2.2.0**

Tested on **debian 11**

### Current Behavior:
Naabu does not work if ipv6 is disabled on kernel level
```
naabu -Pn -host 192.168.0.0/24 -ip-version 4

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

		projectdiscovery.io

[INF] Current naabu version 2.2.0 (latest)
[FTL] Could not create runner: listen ip6:tcp : socket: address family not supported by protocol
```

IPv6 status on my debian
```
cat /sys/module/ipv6/parameters/disable
1
```

### Expected Behavior:
Scan should start if ipv6 is disabled
or
We should have the possibility to disable ipv6 with a parameter (set `-ip-version 4` does not work)

### Steps To Reproduce:
- Add `ipv6.disable=1` to your `/etc/default/grub`, launch `update-grub` and reboot
![image](https://github.com/projectdiscovery/naabu/assets/1230954/ed6c2c13-0e0d-478a-a1c2-1becf3db6681)
![image](https://github.com/projectdiscovery/naabu/assets/1230954/77cbbb25-6553-4d12-afd0-7f391942b094)
- Launch a naabu scan

**Comment by Mzack9999** [comment]
Closing as this should be fixed with https://github.com/projectdiscovery/naabu/pull/946 - Feel free to reopen if the error persist
