### ISSUE TITLE
-t flag doesn't work properly on Ubuntu

### ISSUE THREAD

**Issue by w9w** [projectdiscovery/naabu#936]
### Naabu version:
2.2.1 (latest)

### Current Behavior:
When executing `naabu -list ~/domains/vercel.sh/subds.txt -t -` on Ubuntu (-t - is for all ports per the docs), I'm getting an error `flag provided but not defined: -t`

**Comment by ehsandeep** [comment]
> -t - is for all ports per the docs

@w9w can you point the link of docs or where you reading this?
