### ISSUE TITLE
[FTL] Could not run enumeration: no targets specified

### ISSUE THREAD

**Issue by z3dc0ps** [projectdiscovery/naabu#98]
naabu -source-ip 172.217.160.142

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.2

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running TCP/ICMP/SYN scan with root privileges
[FTL] Could not run enumeration: no targets specified

![Capture](https://user-images.githubusercontent.com/61974788/96090413-c88e4a00-0ee5-11eb-8902-3a6cd97381eb.PNG)

**Comment by bauthard** [comment]
Hey @z3dc0ps, 

You need to use `-host` flag to provide a target. 

```
naabu -silent -host 172.217.160.142
172.217.160.142:80
172.217.160.142:443
```
