### ISSUE TITLE
Not Scanning HTB Boxes

### ISSUE THREAD

**Issue by z3dc0ps** [projectdiscovery/naabu#99]
![Capture](https://user-images.githubusercontent.com/61974788/96097997-4145d400-0eef-11eb-9ff0-e87cd1cdb756.PNG)

**Comment by team-projectdiscovery** [comment]
This is fixed in the master code and will be usable with new release using connect scan! 

```
naabu -host 10.10.10.209 -s c
```
```

**Comment by z3dc0ps** [comment]
For me it showing `-s` not defined
![bug](https://user-images.githubusercontent.com/61974788/101765382-3ed6b380-3b07-11eb-8054-47ccbce6463e.PNG)
