### ISSUE TITLE
-exclude-ports Flag Fails to Function Correctly When Used Alongside -passive Flag

### ISSUE THREAD

**Issue by abd-4fg** [projectdiscovery/naabu#998]
The -exclude-ports is not working properly , i have kept these two ports as exluded :
naabu -l domains.txt -exclude-ports 80,443  -o output.txt
However , still i am getting domains with :443 or :80 in the output file.

### Naabu version:
2.3.0

**Comment by dogancanbakir** [comment]
Thanks for opening this issue. I couldn't repro the issue:

with `exclude-ports`
```console
$go run . -host hackerone.com -top-ports 1000 -exclude-ports 80,443

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.3.0 (latest)
[INF] Running CONNECT scan with non root privileges
hackerone.com:8443
hackerone.com:8080
[INF] Found 2 ports on host hackerone.com (172.64.151.42)
```

without `exclude-ports`:
```console
$ go run . -host hackerone.com -top-ports 1000                      

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.3.0 (latest)
[INF] Running CONNECT scan with non root privileges
hackerone.com:443
hackerone.com:8443
hackerone.com:8080
hackerone.com:80
[INF] Found 4 ports on host hackerone.com (104.18.36.214)
```

Do you mind sharing your repro steps, including hosts? Over Discord, maybe?

**Comment by abd-4fg** [comment]
Hi , 
I guess i found the cause of this problem i have :
It looks like when having -passive `(grepping open ports from shodan)` flag in command , it ignores -exclude-ports
![image](https://github.com/projectdiscovery/naabu/assets/81921899/95d769a3-e9b0-42c2-bf30-bf3f626e862f)

Is this intentional or bug ?
